# Issue #356 — selective third-outcome protection

Executed decision notebook. P is frozen on 2019–2021; 2022–2024 are exposed transfer.

In [1]:
from pathlib import Path
import json
import pandas as pd
repo = Path.cwd()
output = repo / 'results/low_n_third_outcome_protection'
decision = json.loads((output / 'decision.json').read_text())
selected = pd.read_csv(output / 'selected_p.csv')
performance = pd.read_csv(output / 'performance.csv')
contrasts = pd.read_csv(output / 'contrasts.csv')
risk = pd.read_csv(output / 'risk.csv')
attribution = pd.read_csv(output / 'protection_attribution.csv')
rank_diagnostics = pd.read_csv(output / 'rank_diagnostics.csv')
development = pd.read_csv(output / 'development_contrasts.csv')
decision

{'changes_210_or_218': False,
 'contract': 'BJ-UNIFIED-LOWN-THIRD-OUTCOME-PROTECTION-001/v1',
 'diagnostic_sleeves_are_exposed': True,
 'issue': 356,
 'primary_decision_only_s0': True,
 'production_or_holdout_authorized': False,
 'selected_p_results': [{'bootstrap_mean_lift_p05_cny': -302.124066445924,
   'development_gate_pass': True,
   'historical_signal': False,
   'lane': 'S0_N3',
   'n': 3,
   'path_risk_gate': False,
   'primary_lane': True,
   'robust_historical_signal': False,
   'selected_p': 2,
   'transfer_ex_largest_lift_cny': -18273.926624611886,
   'transfer_lift_cny': -19871.358464507837,
   'transfer_positive_years': 0},
  {'bootstrap_mean_lift_p05_cny': -333.85571374738043,
   'development_gate_pass': True,
   'historical_signal': False,
   'lane': 'S0_N4',
   'n': 4,
   'path_risk_gate': False,
   'primary_lane': True,
   'robust_historical_signal': False,
   'selected_p': 3,
   'transfer_ex_largest_lift_cny': -16695.872738812242,
   'transfer_lift_cny': -17008.408516829186,
   'transfer_positive_years': 1},
  {'bootstrap_mean_lift_p05_cny': -518.9399478086159,
   'development_gate_pass': True,
   'historical_signal': False,
   'lane': 'S0_N5',
   'n': 5,
   'path_risk_gate': False,
   'primary_lane': True,
   'robust_historical_signal': False,
   'selected_p': 5,
   'transfer_ex_largest_lift_cny': -33820.8846974618,
   'transfer_lift_cny': -39011.16206810842,
   'transfer_positive_years': 1},
  {'bootstrap_mean_lift_p05_cny': 0.0,
   'development_gate_pass': False,
   'historical_signal': False,
   'lane': 'N3_VALUE',
   'n': 3,
   'path_risk_gate': True,
   'primary_lane': False,
   'robust_historical_signal': False,
   'selected_p': 0,
   'transfer_ex_largest_lift_cny': 0.0,
   'transfer_lift_cny': 0.0,
   'transfer_positive_years': 0},
  {'bootstrap_mean_lift_p05_cny': -373.19713864962,
   'development_gate_pass': True,
   'historical_signal': False,
   'lane': 'N4_COVERAGE_VALUE',
   'n': 4,
   'path_risk_gate': False,
   'primary_lane': False,
   'robust_historical_signal': False,
   'selected_p': 4,
   'transfer_ex_largest_lift_cny': -32083.71568721119,
   'transfer_lift_cny': -32681.236383825395,
   'transfer_positive_years': 0}],
 'verdict': 'NO_INCREMENT'}

In [2]:
selected

,lane,n,p,primary_lane,development_positive_years,development_lift_cny,development_ex_largest_lift_cny,development_hit_rate_lift,development_risk_gate,development_gate_pass
0,S0_N3,3,2,True,2,6259.068379,10187.545965,0.305344,True,True
1,S0_N4,4,3,True,3,26412.184348,25291.561508,0.406250,True,True
2,S0_N5,5,5,True,3,29014.632041,28192.407106,0.640000,True,True
3,N3_VALUE,3,0,False,0,0.000000,0.000000,0.000000,True,False
4,N4_COVERAGE_VALUE,4,4,False,3,11907.028491,13276.001576,0.580357,True,True

In [3]:
development[development.period.eq('ALL_2019_2021')].sort_values(['lane','n','p'])

,lane,primary_lane,n,p,period,common_issues,common_bet_issues,p0_pnl_cny,candidate_pnl_cny,pnl_lift_cny,...,p0_longest_losing_run,p0_completed_recovery_issues,p0_open_underwater_issues,p0_recovery_censored,candidate_max_drawdown_cny,candidate_max_drawdown_fraction,candidate_longest_losing_run,candidate_completed_recovery_issues,candidate_open_underwater_issues,candidate_recovery_censored
3,N3_VALUE,False,3,0,ALL_2019_2021,138,90,-25664.137808,-25664.137808,0.000000,...,8,0,138,True,26973.305039,0.269733,8,0,138,True
7,N3_VALUE,False,3,1,ALL_2019_2021,138,90,-25664.137808,-31021.335885,-5357.198077,...,8,0,138,True,35339.899819,0.352418,7,0,137,True
11,N3_VALUE,False,3,2,ALL_2019_2021,138,90,-25664.137808,-26367.137725,-702.999916,...,8,0,138,True,27615.151683,0.276152,6,0,138,True
15,N3_VALUE,False,3,3,ALL_2019_2021,138,90,-25664.137808,-23787.547608,1876.590200,...,8,0,138,True,24675.189312,0.246174,7,2,133,True
19,N4_COVERAGE_VALUE,False,4,0,ALL_2019_2021,139,112,-51501.820165,-51501.820165,0.000000,...,11,0,139,True,55205.263760,0.552053,11,0,139,True
23,N4_COVERAGE_VALUE,False,4,1,ALL_2019_2021,139,112,-51501.820165,-38655.117635,12846.702529,...,11,0,139,True,40449.068107,0.404491,14,0,139,True
27,N4_COVERAGE_VALUE,False,4,2,ALL_2019_2021,139,112,-51501.820165,-40471.791926,11030.028238,...,11,0,139,True,40828.266869,0.408283,14,0,139,True
31,N4_COVERAGE_VALUE,False,4,3,ALL_2019_2021,139,112,-51501.820165,-42123.805283,9378.014882,...,11,0,139,True,42123.805283,0.421238,12,0,139,True
35,N4_COVERAGE_VALUE,False,4,4,ALL_2019_2021,139,112,-51501.820165,-39594.791674,11907.028491,...,11,0,139,True,39763.067228,0.397631,11,0,139,True
39,S0_N3,True,3,0,ALL_2019_2021,131,131,-46361.069916,-46361.069916,0.000000,...,12,0,131,True,47670.237147,0.476702,12,0,131,True
43,S0_N3,True,3,1,ALL_2019_2021,131,131,-46361.069916,-44784.212108,1576.857808,...,12,0,131,True,49313.299453,0.491612,11,0,130,True
47,S0_N3,True,3,2,ALL_2019_2021,131,131,-46361.069916,-40102.001537,6259.068379,...,12,0,131,True,40867.748676,0.408677,13,0,131,True
51,S0_N3,True,3,3,ALL_2019_2021,131,131,-46361.069916,-47865.640583,-1504.570668,...,12,0,131,True,49245.530227,0.488901,29,2,129,True
55,S0_N4,True,4,0,ALL_2019_2021,128,128,-65482.878453,-65482.878453,0.000000,...,25,0,128,True,68143.180495,0.681432,25,0,128,True
59,S0_N4,True,4,1,ALL_2019_2021,128,128,-65482.878453,-47015.756536,18467.121917,...,25,0,128,True,50626.627031,0.504939,16,0,127,True
63,S0_N4,True,4,2,ALL_2019_2021,128,128,-65482.878453,-42562.450583,22920.427871,...,25,0,128,True,43597.105148,0.435971,11,0,128,True
67,S0_N4,True,4,3,ALL_2019_2021,128,128,-65482.878453,-39070.694105,26412.184348,...,25,0,128,True,39082.904054,0.390829,10,0,128,True
71,S0_N4,True,4,4,ALL_2019_2021,128,128,-65482.878453,-39314.189655,26168.688799,...,25,0,128,True,41197.403646,0.404874,15,2,126,True
75,S0_N5,True,5,0,ALL_2019_2021,125,125,-60301.946652,-60301.946652,0.000000,...,18,0,125,True,65599.018925,0.655990,18,0,125,True
79,S0_N5,True,5,1,ALL_2019_2021,125,125,-60301.946652,-52727.318555,7574.628097,...,18,0,125,True,57254.872669,0.570811,13,9,116,True
83,S0_N5,True,5,2,ALL_2019_2021,125,125,-60301.946652,-31265.409904,29036.536747,...,18,0,125,True,42477.384179,0.401244,11,30,95,True
87,S0_N5,True,5,3,ALL_2019_2021,125,125,-60301.946652,-30647.826676,29654.119975,...,18,0,125,True,36213.674150,0.362137,20,0,125,True
91,S0_N5,True,5,4,ALL_2019_2021,125,125,-60301.946652,-32705.189773,27596.756879,...,18,0,125,True,32866.390824,0.328664,11,0,125,True
95,S0_N5,True,5,5,ALL_2019_2021,125,125,-60301.946652,-31287.314611,29014.632041,...,18,0,125,True,32682.325209,0.325340,9,2,123,True

In [4]:
contrasts[contrasts.period.eq('ALL_2022_2024')].sort_values(['lane','n','p'])

,lane,primary_lane,n,p,period,common_issues,common_bet_issues,p0_pnl_cny,candidate_pnl_cny,pnl_lift_cny,...,p0_longest_losing_run,p0_completed_recovery_issues,p0_open_underwater_issues,p0_recovery_censored,candidate_max_drawdown_cny,candidate_max_drawdown_fraction,candidate_longest_losing_run,candidate_completed_recovery_issues,candidate_open_underwater_issues,candidate_recovery_censored
7,N3_VALUE,False,3,0,ALL_2022_2024,160,108,-14529.730475,-14529.730475,0.000000,...,5,3,156,True,23226.905284,0.231739,5,3,156,True
15,N3_VALUE,False,3,1,ALL_2022_2024,160,108,-14529.730475,-16826.281946,-2296.551471,...,5,3,156,True,23810.802288,0.229198,8,33,120,True
23,N3_VALUE,False,3,2,ALL_2022_2024,160,108,-14529.730475,-25417.971053,-10888.240578,...,5,3,156,True,27944.070577,0.272556,9,38,118,True
31,N3_VALUE,False,3,3,ALL_2022_2024,160,108,-14529.730475,-38779.844400,-24250.113925,...,5,3,156,True,40924.792224,0.400654,9,40,118,True
39,N4_COVERAGE_VALUE,False,4,0,ALL_2022_2024,161,115,-9399.730891,-9399.730891,0.000000,...,7,45,103,True,16922.144066,0.162340,7,45,103,True
47,N4_COVERAGE_VALUE,False,4,1,ALL_2022_2024,161,115,-9399.730891,-20394.235047,-10994.504156,...,7,45,103,True,21211.774720,0.210558,8,3,152,True
55,N4_COVERAGE_VALUE,False,4,2,ALL_2022_2024,161,115,-9399.730891,-16712.076651,-7312.345760,...,7,45,103,True,21987.769150,0.213995,8,5,150,True
63,N4_COVERAGE_VALUE,False,4,3,ALL_2022_2024,161,115,-9399.730891,-28094.406251,-18694.675359,...,7,45,103,True,29695.513028,0.292275,9,2,156,True
71,N4_COVERAGE_VALUE,False,4,4,ALL_2022_2024,161,115,-9399.730891,-42080.967275,-32681.236384,...,7,45,103,True,42620.492960,0.423918,13,16,142,True
79,S0_N3,True,3,0,ALL_2022_2024,154,154,-19322.035729,-19322.035729,0.000000,...,15,7,143,True,28692.504599,0.283240,15,7,143,True
87,S0_N3,True,3,1,ALL_2022_2024,154,154,-19322.035729,-27889.743390,-8567.707661,...,15,7,143,True,31815.501151,0.311399,16,38,116,True
95,S0_N3,True,3,2,ALL_2022_2024,154,154,-19322.035729,-39193.394194,-19871.358465,...,15,7,143,True,40884.591540,0.402047,21,0,151,True
103,S0_N3,True,3,3,ALL_2022_2024,154,154,-19322.035729,-50033.364453,-30711.328723,...,15,7,143,True,50460.077091,0.502457,18,39,114,True
111,S0_N4,True,4,0,ALL_2022_2024,153,153,-14749.488360,-14749.488360,0.000000,...,8,10,142,True,26627.871818,0.265036,8,10,142,True
119,S0_N4,True,4,1,ALL_2022_2024,153,153,-14749.488360,-31136.617509,-16387.129149,...,8,10,142,True,34834.460296,0.345539,11,3,150,True
127,S0_N4,True,4,2,ALL_2022_2024,153,153,-14749.488360,-18256.615486,-3507.127127,...,8,10,142,True,21906.589049,0.219066,15,0,153,True
135,S0_N4,True,4,3,ALL_2022_2024,153,153,-14749.488360,-31757.896877,-17008.408517,...,8,10,142,True,33221.279798,0.327421,16,2,150,True
143,S0_N4,True,4,4,ALL_2022_2024,153,153,-14749.488360,-45332.144717,-30582.656357,...,8,10,142,True,46830.189000,0.461390,16,39,113,True
151,S0_N5,True,5,0,ALL_2022_2024,153,153,-14414.605758,-14414.605758,0.000000,...,8,16,125,True,29214.456581,0.265262,8,16,125,True
159,S0_N5,True,5,1,ALL_2022_2024,153,153,-14414.605758,-22969.529098,-8554.923339,...,8,16,125,True,34788.277637,0.332126,13,7,142,True
167,S0_N5,True,5,2,ALL_2022_2024,153,153,-14414.605758,-15796.363187,-1381.757429,...,8,16,125,True,29004.892561,0.268857,12,38,115,True
175,S0_N5,True,5,3,ALL_2022_2024,153,153,-14414.605758,-26143.415797,-11728.810038,...,8,16,125,True,30493.071687,0.304931,15,0,153,True
183,S0_N5,True,5,4,ALL_2022_2024,153,153,-14414.605758,-40275.935275,-25861.329516,...,8,16,125,True,40526.532249,0.404252,16,0,152,True
191,S0_N5,True,5,5,ALL_2022_2024,153,153,-14414.605758,-53425.767827,-39011.162068,...,8,16,125,True,53425.767827,0.534258,18,0,153,True

In [5]:
performance[performance.period.eq('ALL_2022_2024')].sort_values(['lane','n','p'])

,lane,primary_lane,n,p,period,evaluable_issues,bet_issues,no_bet_issues,stake_cny,gross_cny,pnl_cny,ending_capital_cny,capital_return,stake_roi,hit_rate_per_bet,largest_payout_share,payout_hhi
7,N3_VALUE,False,3,0,ALL_2022_2024,160,108,52,110592,96062.269525,-14529.730475,85470.269525,-0.145297,-0.131381,0.620370,0.049451,0.020443
15,N3_VALUE,False,3,1,ALL_2022_2024,160,108,52,110592,93765.718054,-16826.281946,83173.718054,-0.168263,-0.152147,0.740741,0.095644,0.024415
23,N3_VALUE,False,3,2,ALL_2022_2024,160,108,52,110592,85174.028947,-25417.971053,74582.028947,-0.254180,-0.229836,0.879630,0.072701,0.021916
31,N3_VALUE,False,3,3,ALL_2022_2024,160,108,52,110592,71812.155600,-38779.844400,61220.155600,-0.387798,-0.350657,1.000000,0.057528,0.019449
39,N4_COVERAGE_VALUE,False,4,0,ALL_2022_2024,161,115,46,117760,108360.269109,-9399.730891,90600.269109,-0.093997,-0.079821,0.530435,0.051332,0.024233
47,N4_COVERAGE_VALUE,False,4,1,ALL_2022_2024,161,115,46,117760,97365.764953,-20394.235047,79605.764953,-0.203942,-0.173185,0.626087,0.042840,0.020649
55,N4_COVERAGE_VALUE,False,4,2,ALL_2022_2024,161,115,46,117760,101047.923349,-16712.076651,83287.923349,-0.167121,-0.141916,0.747826,0.082195,0.024653
63,N4_COVERAGE_VALUE,False,4,3,ALL_2022_2024,161,115,46,117760,89665.593749,-28094.406251,71905.593749,-0.280944,-0.238573,0.895652,0.066164,0.019184
71,N4_COVERAGE_VALUE,False,4,4,ALL_2022_2024,161,115,46,117760,75679.032725,-42080.967275,57919.032725,-0.420810,-0.357345,1.000000,0.065603,0.018681
79,S0_N3,True,3,0,ALL_2022_2024,154,154,0,157696,138373.964271,-19322.035729,80677.964271,-0.193220,-0.122527,0.603896,0.054751,0.017347
87,S0_N3,True,3,1,ALL_2022_2024,154,154,0,157696,129806.256610,-27889.743390,72110.256610,-0.278897,-0.176858,0.701299,0.070733,0.019535
95,S0_N3,True,3,2,ALL_2022_2024,154,154,0,157696,118502.605806,-39193.394194,60806.605806,-0.391934,-0.248538,0.844156,0.050452,0.016169
103,S0_N3,True,3,3,ALL_2022_2024,154,154,0,157696,107662.635547,-50033.364453,49966.635547,-0.500334,-0.317277,1.000000,0.038372,0.013240
111,S0_N4,True,4,0,ALL_2022_2024,153,153,0,156672,141922.511640,-14749.488360,85250.511640,-0.147495,-0.094142,0.496732,0.049214,0.019800
119,S0_N4,True,4,1,ALL_2022_2024,153,153,0,156672,125535.382491,-31136.617509,68863.382491,-0.311366,-0.198738,0.568627,0.075019,0.020677
127,S0_N4,True,4,2,ALL_2022_2024,153,153,0,156672,138415.384514,-18256.615486,81743.384514,-0.182566,-0.116528,0.705882,0.074983,0.022850
135,S0_N4,True,4,3,ALL_2022_2024,153,153,0,156672,124914.103123,-31757.896877,68242.103123,-0.317579,-0.202703,0.849673,0.053414,0.018305
143,S0_N4,True,4,4,ALL_2022_2024,153,153,0,156672,111339.855283,-45332.144717,54667.855283,-0.453321,-0.289344,1.000000,0.062646,0.016652
151,S0_N5,True,5,0,ALL_2022_2024,153,153,0,156672,142257.394242,-14414.605758,85585.394242,-0.144146,-0.092005,0.398693,0.066288,0.027163
159,S0_N5,True,5,1,ALL_2022_2024,153,153,0,156672,133702.470902,-22969.529098,77030.470902,-0.229695,-0.146609,0.470588,0.069123,0.026418
167,S0_N5,True,5,2,ALL_2022_2024,153,153,0,156672,140875.636813,-15796.363187,84203.636813,-0.157964,-0.100824,0.594771,0.105332,0.027064
175,S0_N5,True,5,3,ALL_2022_2024,153,153,0,156672,130528.584203,-26143.415797,73856.584203,-0.261434,-0.166867,0.705882,0.081201,0.024356
183,S0_N5,True,5,4,ALL_2022_2024,153,153,0,156672,116396.064725,-40275.935275,59724.064725,-0.402759,-0.257072,0.849673,0.054636,0.018801
191,S0_N5,True,5,5,ALL_2022_2024,153,153,0,156672,103246.232173,-53425.767827,46574.232173,-0.534258,-0.341004,1.000000,0.041063,0.015287

In [6]:
risk[risk.period.eq('ALL_2022_2024')].sort_values(['lane','n','p'])

,lane,n,p,period,max_drawdown_cny,max_drawdown_fraction,longest_losing_run,completed_recovery_issues,open_underwater_issues,recovery_censored
7,N3_VALUE,3,0,ALL_2022_2024,23226.905284,0.231739,5,3,156,True
15,N3_VALUE,3,1,ALL_2022_2024,23810.802288,0.229198,8,33,120,True
23,N3_VALUE,3,2,ALL_2022_2024,27944.070577,0.272556,9,38,118,True
31,N3_VALUE,3,3,ALL_2022_2024,40924.792224,0.400654,9,40,118,True
39,N4_COVERAGE_VALUE,4,0,ALL_2022_2024,16922.144066,0.162340,7,45,103,True
47,N4_COVERAGE_VALUE,4,1,ALL_2022_2024,21211.774720,0.210558,8,3,152,True
55,N4_COVERAGE_VALUE,4,2,ALL_2022_2024,21987.769150,0.213995,8,5,150,True
63,N4_COVERAGE_VALUE,4,3,ALL_2022_2024,29695.513028,0.292275,9,2,156,True
71,N4_COVERAGE_VALUE,4,4,ALL_2022_2024,42620.492960,0.423918,13,16,142,True
79,S0_N3,3,0,ALL_2022_2024,28692.504599,0.283240,15,7,143,True
87,S0_N3,3,1,ALL_2022_2024,31815.501151,0.311399,16,38,116,True
95,S0_N3,3,2,ALL_2022_2024,40884.591540,0.402047,21,0,151,True
103,S0_N3,3,3,ALL_2022_2024,50460.077091,0.502457,18,39,114,True
111,S0_N4,4,0,ALL_2022_2024,26627.871818,0.265036,8,10,142,True
119,S0_N4,4,1,ALL_2022_2024,34834.460296,0.345539,11,3,150,True
127,S0_N4,4,2,ALL_2022_2024,21906.589049,0.219066,15,0,153,True
135,S0_N4,4,3,ALL_2022_2024,33221.279798,0.327421,16,2,150,True
143,S0_N4,4,4,ALL_2022_2024,46830.189000,0.461390,16,39,113,True
151,S0_N5,5,0,ALL_2022_2024,29214.456581,0.265262,8,16,125,True
159,S0_N5,5,1,ALL_2022_2024,34788.277637,0.332126,13,7,142,True
167,S0_N5,5,2,ALL_2022_2024,29004.892561,0.268857,12,38,115,True
175,S0_N5,5,3,ALL_2022_2024,30493.071687,0.304931,15,0,153,True
183,S0_N5,5,4,ALL_2022_2024,40526.532249,0.404252,16,0,152,True
191,S0_N5,5,5,ALL_2022_2024,53425.767827,0.534258,18,0,153,True

In [7]:
attribution[attribution.period.eq('ALL_2022_2024')].sort_values(['lane','n','p'])

,lane,n,p,period,settled_bet_issues,baseline_hit_issues,baseline_one_miss_issues,baseline_two_plus_miss_issues,salvaged_issues,salvaged_one_miss_issues,salvaged_two_plus_miss_issues,salvage_gross_cny,incumbent_hit_dilution_cny
7,N3_VALUE,3,0,ALL_2022_2024,108,67,30,11,0,0,0,0.000000,0.000000
15,N3_VALUE,3,1,ALL_2022_2024,108,67,30,11,13,13,0,29703.381275,-31999.932746
23,N3_VALUE,3,2,ALL_2022_2024,108,67,30,11,28,24,4,42456.793880,-53345.034458
31,N3_VALUE,3,3,ALL_2022_2024,108,67,30,11,41,30,11,43333.498353,-67583.612278
39,N4_COVERAGE_VALUE,4,0,ALL_2022_2024,115,61,36,18,0,0,0,0.000000,0.000000
47,N4_COVERAGE_VALUE,4,1,ALL_2022_2024,115,61,36,18,11,11,0,25589.236840,-36583.740997
55,N4_COVERAGE_VALUE,4,2,ALL_2022_2024,115,61,36,18,25,21,4,52855.410223,-60167.755983
63,N4_COVERAGE_VALUE,4,3,ALL_2022_2024,115,61,36,18,42,31,11,57567.877931,-76262.553290
71,N4_COVERAGE_VALUE,4,4,ALL_2022_2024,115,61,36,18,54,36,18,54457.881556,-87139.117940
79,S0_N3,3,0,ALL_2022_2024,154,93,46,15,0,0,0,0.000000,0.000000
87,S0_N3,3,1,ALL_2022_2024,154,93,46,15,15,15,0,37391.419820,-45959.127481
95,S0_N3,3,2,ALL_2022_2024,154,93,46,15,37,33,4,57192.004207,-77063.362671
103,S0_N3,3,3,ALL_2022_2024,154,93,46,15,61,46,15,66732.186144,-97443.514868
111,S0_N4,4,0,ALL_2022_2024,153,76,54,23,0,0,0,0.000000,0.000000
119,S0_N4,4,1,ALL_2022_2024,153,76,54,23,11,11,0,31123.505247,-47510.634395
127,S0_N4,4,2,ALL_2022_2024,153,76,54,23,32,30,2,75638.591488,-79145.718615
135,S0_N4,4,3,ALL_2022_2024,153,76,54,23,54,43,11,82436.981720,-99445.390237
143,S0_N4,4,4,ALL_2022_2024,153,76,54,23,77,54,23,82955.043922,-113537.700278
151,S0_N5,5,0,ALL_2022_2024,153,61,60,32,0,0,0,0.000000,0.000000
159,S0_N5,5,1,ALL_2022_2024,153,61,60,32,11,11,0,39167.637497,-47722.560837
167,S0_N5,5,2,ALL_2022_2024,153,61,60,32,30,28,2,77991.611674,-79373.369102
175,S0_N5,5,3,ALL_2022_2024,153,61,60,32,47,39,8,88191.558239,-99920.368278
183,S0_N5,5,4,ALL_2022_2024,153,61,60,32,69,51,18,88918.449205,-114779.778721
191,S0_N5,5,5,ALL_2022_2024,153,61,60,32,92,60,32,84234.987138,-123246.149206

In [8]:
rank_diagnostics[rank_diagnostics.period.eq('ALL_2022_2024')].sort_values(['lane','n','protection_rank'])

,lane,n,protection_rank,period,evaluated_fixtures,predicted_top2_miss_rate,observed_top2_miss_rate,calibration_error
7,N3_VALUE,3,1,ALL_2022_2024,117,0.212708,0.162393,-0.050315
15,N3_VALUE,3,2,ALL_2022_2024,115,0.194052,0.173913,-0.020139
23,N3_VALUE,3,3,ALL_2022_2024,116,0.181098,0.137931,-0.043167
31,N4_COVERAGE_VALUE,4,1,ALL_2022_2024,123,0.193848,0.178862,-0.014987
39,N4_COVERAGE_VALUE,4,2,ALL_2022_2024,125,0.190227,0.160000,-0.030227
47,N4_COVERAGE_VALUE,4,3,ALL_2022_2024,123,0.186414,0.170732,-0.015682
55,N4_COVERAGE_VALUE,4,4,ALL_2022_2024,122,0.178876,0.122951,-0.055925
63,S0_N3,3,1,ALL_2022_2024,167,0.210651,0.149701,-0.060950
71,S0_N3,3,2,ALL_2022_2024,164,0.191532,0.176829,-0.014703
79,S0_N3,3,3,ALL_2022_2024,166,0.178926,0.162651,-0.016275
87,S0_N4,4,1,ALL_2022_2024,167,0.217119,0.125749,-0.091370
95,S0_N4,4,2,ALL_2022_2024,169,0.197889,0.207101,0.009211
103,S0_N4,4,3,ALL_2022_2024,165,0.188331,0.175758,-0.012574
111,S0_N4,4,4,ALL_2022_2024,167,0.178317,0.167665,-0.010652
119,S0_N5,5,1,ALL_2022_2024,169,0.222202,0.130178,-0.092025
127,S0_N5,5,2,ALL_2022_2024,167,0.203821,0.191617,-0.012204
135,S0_N5,5,3,ALL_2022_2024,168,0.194260,0.190476,-0.003784
143,S0_N5,5,4,ALL_2022_2024,169,0.187110,0.165680,-0.021429
151,S0_N5,5,5,ALL_2022_2024,167,0.178119,0.167665,-0.010455