# #378 corrected N6 vs corrected-N7 portfolio diagnostic

Contract: `BJ-UNIFIED-N6-N7-PORTFOLIO-001/v2`. Executed notebook over the frozen accepted surfaces (#381/#377/#373). All values deterministic.

In [1]:
import pandas as pd, numpy as np
from pathlib import Path
OUT = Path('results/n6_n7_portfolio')
pd.set_option('display.width', 220)
pd.set_option('display.max_columns', 50)

In [2]:
perf = pd.read_csv(OUT/'performance.csv'); perf.head(3)

    path scope  issues  stake_cny     gross_cny       pnl_cny  ending_capital_cny  capital_return  stake_roi  ex_largest_pnl_cny  largest_abs_delta_cny  largest_delta_issue  ex_largest_delta_pnl_cny
0  N6_R3  2022      51      52224  23678.579949 -28545.420051        71454.579949       -0.285454  -0.546596       -32582.189292            4036.769242                22033             -32582.189292
1  N6_R3  2023      47      48128  45429.109821  -2698.890179        97301.109821       -0.026989  -0.056077       -26358.596824           23659.706644                23021             -26358.596824
2  N6_R3  2024      54      55296  74240.320588  18944.320588       118944.320588        0.189443   0.342598         2414.293307           16530.027281                24104               2414.293307

In [3]:
corr = pd.read_csv(OUT/'correlation_diagnostics.csv'); corr

              pair                   kind  issues  pearson_r     pearson_p  spearman_rho    spearman_p
0  N6_R3_x_N7_C0E0                   pool     151   0.753958  5.555383e-29      0.730520  1.848675e-26
1  N6_R3_x_N7_C1E2              mechanism     151   0.374346  2.188941e-06      0.416543  1.038627e-07
2  N6_R3_x_N7_C1E3              mechanism     151   0.235381  3.621619e-03      0.409305  1.805974e-07
3  N6_R0_x_N7_C0E0  benchmark_sensitivity     151   0.038879  6.355258e-01      0.244903  2.439836e-03
4    N6_R3_x_N6_R3        internal_sanity     151   1.000000  0.000000e+00      1.000000  0.000000e+00

In [4]:
assoc = pd.read_csv(OUT/'association_rates.csv'); assoc

                        metric         value
0                common_issues  1.510000e+02
1           n6_profitable_rate  2.185430e-01
2           n7_profitable_rate  1.589404e-01
3         both_profitable_rate  1.390728e-01
4      n6_only_profitable_rate  7.947020e-02
5      n7_only_profitable_rate  1.986755e-02
6      neither_profitable_rate  7.615894e-01
7   phi_profitable_association  6.905402e-01
8                       chi2_p  2.147923e-17
9     both_gross_positive_rate  1.589404e-01
10        both_ticket_hit_rate  1.589404e-01
11          n6_ticket_hit_rate  2.384106e-01
12          n7_ticket_hit_rate  1.721854e-01

In [5]:
pd.read_csv(OUT/'losing_dependence.csv').T

                                       0
common_issues                 151.000000
both_losing_issues            115.000000
both_losing_rate                0.761589
joint_losing_run_max           18.000000
joint_losing_run_count         27.000000
joint_losing_run_p75            4.500000
both_losing_pearson_r           0.931426
n6_underwater_issues          151.000000
n7_underwater_issues          147.000000
both_underwater_issues        147.000000
both_underwater_rate            0.967105
underwater_jaccard              0.973510
drawdown_depth_overlap_ratio    0.619737

In [6]:
pd.read_csv(OUT/'tail_overlap.csv')

    k           table  intersection   jaccard  issue_n6  issue_n7  n6_gross_cny  n7_gross_cny n6_also_gross_positive_on_n7_largest n7_also_gross_positive_on_n6_largest
0   5           gross             3  0.428571       NaN       NaN           NaN           NaN                                  NaN                                  NaN
1   5             pnl             3  0.428571       NaN       NaN           NaN           NaN                                  NaN                                  NaN
2  10           gross             5  0.333333       NaN       NaN           NaN           NaN                                  NaN                                  NaN
3  10             pnl             5  0.333333       NaN       NaN           NaN           NaN                                  NaN                                  NaN
4  20           gross            14  0.538462       NaN       NaN           NaN           NaN                                  NaN                                  NaN
5  20             pnl            14  0.538462       NaN       NaN           NaN           NaN                                  NaN                                  NaN
6   1  largest_payout             1       NaN   23021.0   23021.0  24683.706644  60938.382111                                 True                                 True

In [7]:
perf = pd.read_csv(OUT/'performance.csv'); perf[perf.scope.eq('ALL')]

               path scope  issues  stake_cny      gross_cny       pnl_cny  ending_capital_cny  capital_return  stake_roi  ex_largest_pnl_cny  largest_abs_delta_cny  largest_delta_issue  ex_largest_delta_pnl_cny
3             N6_R3   ALL     152     155648  143348.010358 -12299.989642        87700.010358       -0.123000  -0.079024       -35959.696286           23659.706644                23021             -35959.696286
7           N7_C0E0   ALL     152     154624  187313.126230  32689.126230       132689.126230        0.326891   0.211410       -27225.255881           59914.382111                23021             -27225.255881
11          N7_C1E2   ALL     152     154624  193883.000090  39259.000090       139259.000090        0.392590   0.253900         6763.839531           32495.160559                24104               6763.839531
15          N7_C1E3   ALL     152     154624  187421.518650  32797.518650       132797.518650        0.327975   0.212111         8546.942617           24250.576034                23055               8546.942617
19  PORTFOLIO_50_50   ALL     152     155136  165330.568294  10194.568294       110194.568294        0.101946   0.065714       -31592.476084           36254.675466                23021             -31592.476084
23        N7_HALVED   ALL     152      77312   93656.563115  16344.563115       116344.563115        0.163446   0.211410       -13612.627941           29957.191055                23021             -13612.627941
27     PARALLEL_1_1   ALL     152     155648  330661.136588  20389.136588       120389.136588        0.203891   0.130995       -63184.952167           36254.675466                23021             -63184.952167
31    MECHANICAL_WA   ALL     152     155136  165330.568294  10194.568294       110194.568294        0.101946   0.065714       -31592.476084           36254.675466                23021             -31592.476084

In [8]:
pd.read_csv(OUT/'risk_diagnostics.csv')

               path scope  issues  max_drawdown_fraction  longest_profitable_issue_losing_run  open_underwater_issues  largest_payout_share  payout_hhi
0             N6_R3  2022      51               0.288668                                   17                      51              0.213728    0.145928
1             N6_R3  2023      47               0.207599                                   19                      39              0.543346    0.338849
2             N6_R3  2024      54               0.156484                                    9                       1              0.236449    0.110096
3             N6_R3   ALL     152               0.468927                                   19                     152              0.172194    0.067544
4           N7_C0E0  2022      51               0.331650                                   19                      51              0.285977    0.215921
5           N7_C0E0  2023      47               0.124769                                   19                      38              0.707551    0.523147
6           N7_C0E0  2024      54               0.174977                                    7                       1              0.240748    0.134255
7           N7_C0E0   ALL     152               0.331650                                   19                       1              0.325329    0.136820
8           N7_C1E2  2022      51               0.214356                                   12                      43              0.340905    0.183559
9           N7_C1E2  2023      47               0.178135                                   16                      45              0.282986    0.164577
10          N7_C1E2  2024      54               0.066179                                    7                       8              0.300121    0.140104
11          N7_C1E2   ALL     152               0.308025                                   16                       8              0.172883    0.062087
12          N7_C1E3  2022      51               0.174226                                    6                      51              0.340755    0.171292
13          N7_C1E3  2023      47               0.121011                                    8                       4              0.392481    0.200520
14          N7_C1E3  2024      54               0.074974                                    7                       8              0.207945    0.090456
15          N7_C1E3   ALL     152               0.218967                                    8                       8              0.134854    0.049179
16  PORTFOLIO_50_50  2022      51               0.310159                                   19                      51              0.227431    0.172606
17  PORTFOLIO_50_50  2023      47               0.160883                                   19                      39              0.650847    0.445921
18  PORTFOLIO_50_50  2024      54               0.136753                                    7                       1              0.164286    0.089168
19  PORTFOLIO_50_50   ALL     152               0.322533                                   19                      93              0.258942    0.092833
20        N7_HALVED  2022      51               0.165825                                   19                      51              0.285977    0.215921
21        N7_HALVED  2023      47               0.076566                                   19                      38              0.707551    0.523147
22        N7_HALVED  2024      54               0.087489                                    7                       1              0.240748    0.134255
23        N7_HALVED   ALL     152               0.165825                                   19                       1              0.325329    0.136820
24     PARALLEL_1_1  2022      51               0.620318                                   19                      51              0.227431    0.172606
25     PARALLEL_1_1  2023      47               0.249459                                   19                      39              0.650847    0.445921
26     PARALLEL_1_1  2024      54               0.273506                                    7                       1              0.164286    0.089168
27     PARALLEL_1_1   ALL     152               0.636746                                   19                      93              0.258942    0.092833
28    MECHANICAL_WA  2022      51               0.310159                                   19                      51              0.227431    0.172606
29    MECHANICAL_WA  2023      47               0.160883                                   19                      39              0.650847    0.445921
30    MECHANICAL_WA  2024      54               0.136753                                    7                       1              0.164286    0.089168
31    MECHANICAL_WA   ALL     152               0.322533                                   19                      93              0.258942    0.092833

In [9]:
pd.read_csv(OUT/'matched_contrasts.csv')

,left,right,kind,scope,issues,matched_lift_cny,largest_abs_delta_issue,largest_abs_delta_cny,ex_largest_lift_cny,block_length,draws,lift_p05_cny,lift_median_cny,lift_p95_cny
0,PORTFOLIO_50_50,MECHANICAL_WA,identity_vs_mechanical,2022,51,0.000000,22013,0.000000,0.000000,10,5000,0.000000,0.000000,0.000000
1,PORTFOLIO_50_50,MECHANICAL_WA,identity_vs_mechanical,2023,47,0.000000,23011,0.000000,0.000000,10,5000,0.000000,0.000000,0.000000
2,PORTFOLIO_50_50,MECHANICAL_WA,identity_vs_mechanical,2024,54,0.000000,24011,0.000000,0.000000,10,5000,0.000000,0.000000,0.000000
3,PORTFOLIO_50_50,MECHANICAL_WA,identity_vs_mechanical,ALL,152,0.000000,22013,0.000000,0.000000,10,5000,0.000000,0.000000,0.000000
4,PORTFOLIO_50_50,N7_C0E0,dilution_vs_n7_full,2022,51,-369.219456,22115,-1513.491260,1144.271804,10,5000,-4662.188791,-235.487945,3224.571628
5,PORTFOLIO_50_50,N7_C0E0,dilution_vs_n7_full,2023,47,-20860.352780,23021,-18127.337733,-2733.015047,10,5000,-52911.875629,-20290.758957,1821.089572
6,PORTFOLIO_50_50,N7_C0E0,dilution_vs_n7_full,2024,54,-1264.985699,24081,-9241.158500,7976.172801,10,5000,-23763.752335,-508.067608,18696.233004
7,PORTFOLIO_50_50,N7_C0E0,dilution_vs_n7_full,ALL,152,-22494.557936,23021,-18127.337733,-4367.220202,10,5000,-62095.125723,-20049.600225,10783.030347
8,PORTFOLIO_50_50,N7_HALVED,n6_sleeve_drag_vs_n7_halved,2022,51,-14272.710025,22033,2018.384621,-16291.094646,10,5000,-20913.219459,-14256.841749,-7809.969225
9,PORTFOLIO_50_50,N7_HALVED,n6_sleeve_drag_vs_n7_halved,2023,47,-1349.445090,23021,11829.853322,-13179.298412,10,5000,-18327.241179,-2345.583416,21176.738167
10,PORTFOLIO_50_50,N7_HALVED,n6_sleeve_drag_vs_n7_halved,2024,54,9472.160294,24104,8265.013640,1207.146654,10,5000,-8965.622308,8216.299318,31874.756236
11,PORTFOLIO_50_50,N7_HALVED,n6_sleeve_drag_vs_n7_halved,ALL,152,-6149.994821,23021,11829.853322,-17979.848143,10,5000,-35189.802893,-7379.282870,28053.950367
12,PORTFOLIO_50_50,N6_R3,vs_n6_full,2022,51,369.219456,22115,1513.491260,-1144.271804,10,5000,-3251.039676,234.171085,4478.972050
13,PORTFOLIO_50_50,N6_R3,vs_n6_full,2023,47,20860.352780,23021,18127.337733,2733.015047,10,5000,-1839.884400,19990.759859,52892.572615
14,PORTFOLIO_50_50,N6_R3,vs_n6_full,2024,54,1264.985699,24081,9241.158500,-7976.172801,10,5000,-19297.124619,339.882243,23447.594888
15,PORTFOLIO_50_50,N6_R3,vs_n6_full,ALL,152,22494.557936,23021,18127.337733,4367.220202,10,5000,-11648.750442,21326.484082,60867.956687
16,MECHANICAL_WA,N7_C0E0,mechanical_vs_n7_full,2022,51,-369.219456,22115,-1513.491260,1144.271804,10,5000,-4687.933643,-340.884209,3273.194318
17,MECHANICAL_WA,N7_C0E0,mechanical_vs_n7_full,2023,47,-20860.352780,23021,-18127.337733,-2733.015047,10,5000,-53598.016951,-20101.392895,1289.456896
18,MECHANICAL_WA,N7_C0E0,mechanical_vs_n7_full,2024,54,-1264.985699,24081,-9241.158500,7976.172801,10,5000,-23358.274673,-10.273539,19863.252999
19,MECHANICAL_WA,N7_C0E0,mechanical_vs_n7_full,ALL,152,-22494.557936,23021,-18127.337733,-4367.220202,10,5000,-61911.687818,-21160.308363,10451.742556

In [10]:
pd.read_csv(OUT/'moving_block_async_bootstrap.csv')

                     metric  issues  block_length  draws           p05       median           p95
0        max_drawdown_delta     152            10   5000      0.051242     0.145355      0.351133
1  longest_losing_run_delta     152            10   5000    -12.000000    -1.000000      0.000000
2     open_underwater_delta     152            10   5000    -16.000000     0.000000     94.000000
3        n6_sleeve_drag_cny     152            10   5000 -35132.132184 -6399.678218  26976.607022

In [11]:
pd.read_csv(OUT/'dilution_attribution.csv')

                            component       pnl_cny  capital_return                                               note
0                      n7_full_expert  32689.126230        0.326891             only positive standalone payoff source
1   n7_halved_dilution_counterfactual  16344.563115        0.163446                         pure stake reduction of N7
2                   n6_r3_half_sleeve  -6149.994821       -0.061500                N6 sleeve contribution to portfolio
3                     portfolio_50_50  10194.568294        0.101946                         preregistered 0.5/0.5 path
4         mechanical_weighted_average  10194.568294        0.101946  0.5*N6 + 0.5*N7 over shared calendar (identica...
5                 dilution_vs_n7_full -22494.557936       -0.224946                            portfolio minus N7 full
6         n6_sleeve_drag_vs_n7_halved  -6149.994821       -0.061500                          exactly 0.5*N6 (negative)
7                risk_portfolio_maxdd           NaN        0.322533                    portfolio max drawdown fraction
8                risk_n7_halved_maxdd           NaN        0.165825                  stake-reduction-only max drawdown
9                  risk_n7_full_maxdd           NaN        0.331650                     expert standalone max drawdown
10              async_maxdd_delta_p05           NaN        0.051242  bootstrap p05 of portfolio minus N7-HALVED max DD
11              async_maxdd_delta_p95           NaN        0.351133  bootstrap p95 of portfolio minus N7-HALVED max DD
12                async_run_delta_p05           NaN      -12.000000          bootstrap p05 of longest losing run delta
13                async_run_delta_p95           NaN        0.000000          bootstrap p95 of longest losing run delta

In [12]:
pd.read_csv(OUT/'rolling_windows.csv')

               path  window_issues  windows  worst_window_pnl_cny  p10_window_pnl_cny  median_window_pnl_cny  positive_window_rate
0             N6_R3             20      133         -18941.943999       -14087.155151           -8516.513757              0.263158
1             N6_R3             30      123         -20971.774572       -19591.598836           -9852.855629              0.341463
2             N6_R3             50      103         -32127.968642       -27239.930197           -5770.890179              0.145631
3           N7_C0E0             20      133         -18590.676002       -16164.359797           -7953.967711              0.330827
4           N7_C0E0             30      123         -26404.359797       -23551.075930           -9736.944812              0.439024
5           N7_C0E0             50      103         -31484.806254       -27589.099113           25570.291987              0.621359
6           N7_C1E2             20      133         -15203.196727       -13360.739389            1194.176714              0.526316
7           N7_C1E2             30      123         -18376.601621       -14538.521819            1145.054054              0.512195
8           N7_C1E2             50      103         -19661.127173       -16343.924563            -401.232711              0.475728
9           N7_C1E3             20      133         -13676.924801       -10267.061782            5601.074151              0.684211
10          N7_C1E3             30      123         -17422.633234        -5967.892561            7242.490885              0.731707
11          N7_C1E3             50      103         -14164.495105       -11251.674474           13590.399670              0.786408
12  PORTFOLIO_50_50             20      133         -17772.009399       -14039.554255           -7494.781503              0.308271
13  PORTFOLIO_50_50             30      123         -22459.113868       -19572.168220          -11761.305084              0.382114
14  PORTFOLIO_50_50             50      103         -31806.387448       -26632.099922            9708.740686              0.601942
15        N7_HALVED             20      133          -9295.338001        -8082.179899           -3976.983856              0.330827
16        N7_HALVED             30      123         -13202.179899       -11775.537965           -4868.472406              0.439024
17        N7_HALVED             50      103         -15742.403127       -13794.549557           12785.145994              0.621359
18     PARALLEL_1_1             20      133         -35544.018797       -28079.108509          -14989.563006              0.308271
19     PARALLEL_1_1             30      123         -44918.227735       -39144.336440          -23522.610167              0.382114
20     PARALLEL_1_1             50      103         -63612.774896       -53264.199844           19417.481373              0.601942
21    MECHANICAL_WA             20      133         -17772.009399       -14039.554255           -7494.781503              0.308271
22    MECHANICAL_WA             30      123         -22459.113868       -19572.168220          -11761.305084              0.382114
23    MECHANICAL_WA             50      103         -31806.387448       -26632.099922            9708.740686              0.601942

## Conclusion

No N6 arm is standalone-positive in the complete corrected #381 R0-R6 surface (best R1 -5,447; R0 -33,511; R3 -12,300); #377 retained no mechanism cell. Worse, the payoff sources are synchronized, not asynchronous: issue-PnL Pearson r=0.75, both lose together on 76% of shared issues, and the drawdown bootstrap delta vs the pure stake-reduction counterfactual is entirely positive. The preregistered 50/50 portfolio therefore dilutes the only positive expert (N7 R3 CONTROL) by CNY6,150 and cannot improve holding risk without diluting return.