# Issue #334 neural Top-2 residual learner

Executed decision notebook. The Python package is the source of computation; this notebook exposes completeness, diagnostics and capital attribution.

In [1]:
from pathlib import Path
import json, pandas as pd
ROOT = Path('../../..').resolve()
OUT = ROOT / 'results/neural_top2_residual'
json.loads((OUT / 'decision.json').read_text())

{'accepted_baseline': '#319 P_TOP2_NO_GATE N7 / 512 units / CNY1024',
 'anchor_allocation_only_terminal_ex_largest_lift_cny': 7971.789845858046,
 'anchor_allocation_only_terminal_lift_cny': 6068.204566657,
 'anchor_baseline_advancing_candidate': False,
 'anchor_support_only_terminal_ex_largest_lift_cny': 23919.123308615934,
 'anchor_support_only_terminal_lift_cny': 49393.44830252863,
 'anchor_terminal_bootstrap_positive_fraction': 0.735,
 'anchor_terminal_ex_largest_lift_cny': 3292.5446292231136,
 'anchor_terminal_lift_cny': 28766.86962313581,
 'baseline_advancing_candidate': False,
 'development_median_ex_largest_lift_cny': 2579.443811444493,
 'development_median_lift_cny': 7940.529015204006,
 'disposition': 'ANCHOR_SHRINKAGE_SIGNAL_NOT_YET_PROMOTED',
 'issue': 334,
 'next_interface': 'ANCHOR_SHRINKAGE_REPLICATION',
 'promotion': False,
 'selected_anchor_control': 'ANCHOR_SHRINK_A000',
 'selected_arm': 'S1O0',
 'selected_model': 'MLP32_A010',
 'selection_data': '2023_ONLY',
 'terminal_bootstrap_positive_fraction_median': 0.037,
 'terminal_data': '2024_FROZEN_ONCE',
 'terminal_max_drawdown_fraction_median': 0.26528214991446936,
 'terminal_median_ex_largest_lift_cny': -31786.745946291285,
 'terminal_median_lift_cny': -35277.956815627986,
 'terminal_probability_brier_median': 0.21544658092699623,
 'terminal_shuffled_median_lift_cny': -54011.7604897308,
 'unlock_210': False}

In [2]:
pd.read_csv(OUT / 'cell_coverage.csv')

,issue_year,issues,cells,observable_fraction,source_absent_cells,untrusted_or_invalid_cells,matches
0,2020,38,28899,0.987128,372,0,9633
1,2021,63,62907,0.985884,882,6,20969
2,2022,62,57456,0.988983,627,6,19152
3,2023,53,44025,0.991346,375,6,14675
4,2024,66,54270,0.991321,456,15,18090

In [3]:
pd.read_csv(OUT / 'model_diagnostics.csv').groupby(['model','issue_year']).median(numeric_only=True)[['brier','log_loss','value_mae']]

                                         brier  log_loss  value_mae
model                     issue_year
ANCHOR_SHRINK_A000        2023        0.215359  0.621227   1.344373
                          2024        0.215244  0.621015   1.337361
ANCHOR_SHRINK_A025        2023        0.215359  0.621227   1.350089
                          2024        0.215244  0.621015   1.343102
ANCHOR_SHRINK_A050        2023        0.215359  0.621227   1.355872
                          2024        0.215244  0.621015   1.348949
ANCHOR_SHRINK_A075        2023        0.215359  0.621227   1.361662
                          2024        0.215244  0.621015   1.354820
ANCHOR_SHRINK_A100        2023        0.215359  0.621227   1.367454
                          2024        0.215244  0.621015   1.360697
BASELINE                  2023        0.215359  0.621227   1.344373
                          2024        0.215244  0.621015   1.337361
LINEAR                    2023        0.215338  0.621171   1.376469
                          2024        0.215174  0.621185   1.368888
MLP32_A010                2023        0.215571  0.621754   1.378313
                          2024        0.215447  0.621483   1.371867
MLP32_A010_LABEL_SHUFFLED 2023        0.215535  0.621639   1.357894
                          2024        0.215383  0.621619   1.351465

In [4]:
pd.read_csv(OUT / 'performance.csv').groupby(['model','arm','issue_year']).median(numeric_only=True)[['pnl_cny','matched_lift_cny','ex_largest_lift_cny','ending_capital_cny']]

                                                        pnl_cny  \
model                     arm          issue_year
ANCHOR_SHRINK_A000        S0O0         2023       -13529.625244
                                       2024        14269.187609
                          S0O1         2023        27268.686146
                                       2024        43036.057232
                          S0O1_ALLOC   2023       -11455.336892
...                                                         ...
MLP32_A010_LABEL_SHUFFLED S0O1_SUPPORT 2024        43099.741486
                          S1O0         2023       -15784.380940
                                       2024       -39758.495846
                          S1O1         2023        -8599.794673
                                       2024       -11577.588744

                                                   matched_lift_cny  \
model                     arm          issue_year
ANCHOR_SHRINK_A000        S0O0         2023                0.000000
                                       2024                0.000000
                          S0O1         2023            40798.311390
                                       2024            28766.869623
                          S0O1_ALLOC   2023             2074.288352
...                                                             ...
MLP32_A010_LABEL_SHUFFLED S0O1_SUPPORT 2024            28830.553877
                          S1O0         2023            -4302.755696
                                       2024           -54011.760490
                          S1O1         2023             2881.830571
                                       2024           -26870.776353

                                                   ex_largest_lift_cny  \
model                     arm          issue_year
ANCHOR_SHRINK_A000        S0O0         2023                   0.000000
                                       2024                   0.000000
                          S0O1         2023                4152.724623
                                       2024                3292.544629
                          S0O1_ALLOC   2023                4338.838306
...                                                                ...
MLP32_A010_LABEL_SHUFFLED S0O1_SUPPORT 2024                3356.228883
                          S1O0         2023               -7129.394755
                                       2024              -46718.286551
                          S1O1         2023                1669.160415
                                       2024              -31037.630943

                                                   ending_capital_cny
model                     arm          issue_year
ANCHOR_SHRINK_A000        S0O0         2023              86470.374756
                                       2024             114269.187609
                          S0O1         2023             127268.686146
                                       2024             143036.057232
                          S0O1_ALLOC   2023              88544.663108
...                                                               ...
MLP32_A010_LABEL_SHUFFLED S0O1_SUPPORT 2024             143099.741486
                          S1O0         2023              84215.619060
                                       2024              60241.504154
                          S1O1         2023              91400.205327
                                       2024              88422.411256

[96 rows x 4 columns]

In [5]:
pd.read_csv(OUT / 'factorial_attribution.csv').groupby('issue_year').median(numeric_only=True)

,seed,issues,selection_main_cny,outcome_allocation_main_cny,interaction_cny,joint_lift_cny
issue_year,,,,,,
2023,33403.0,45.0,7940.529015,-30847.623277,36773.995246,10482.548447
2024,33403.0,56.0,-35277.956816,-27552.519844,36737.643786,-25278.135186

In [6]:
pd.read_csv(OUT / 'risk_diagnostics.csv').groupby(['model','arm','issue_year']).median(numeric_only=True)[['max_drawdown_fraction','max_consecutive_losing_issues','worst_rolling_10_cny','max_recovery_issues']]

                                                   max_drawdown_fraction  \
model                     arm          issue_year
ANCHOR_SHRINK_A000        S0O0         2023                     0.259624
                                       2024                     0.116387
                          S0O1         2023                     0.142134
                                       2024                     0.111285
                          S0O1_ALLOC   2023                     0.240396
...                                                                  ...
MLP32_A010_LABEL_SHUFFLED S0O1_SUPPORT 2024                     0.148139
                          S1O0         2023                     0.232036
                                       2024                     0.438181
                          S1O1         2023                     0.183418
                                       2024                     0.233969

                                                   max_consecutive_losing_issues  \
model                     arm          issue_year
ANCHOR_SHRINK_A000        S0O0         2023                                 12.0
                                       2024                                  7.0
                          S0O1         2023                                 17.0
                                       2024                                 10.0
                          S0O1_ALLOC   2023                                 12.0
...                                                                          ...
MLP32_A010_LABEL_SHUFFLED S0O1_SUPPORT 2024                                 10.0
                          S1O0         2023                                 15.0
                                       2024                                 37.0
                          S1O1         2023                                 14.0
                                       2024                                 18.0

                                                   worst_rolling_10_cny  \
model                     arm          issue_year
ANCHOR_SHRINK_A000        S0O0         2023               -10240.000000
                                       2024                -8853.606761
                          S0O1         2023               -10240.000000
                                       2024               -10240.000000
                          S0O1_ALLOC   2023               -10240.000000
...                                                                 ...
MLP32_A010_LABEL_SHUFFLED S0O1_SUPPORT 2024               -10240.000000
                          S1O0         2023               -10240.000000
                                       2024               -10240.000000
                          S1O1         2023               -10240.000000
                                       2024               -10240.000000

                                                   max_recovery_issues
model                     arm          issue_year
ANCHOR_SHRINK_A000        S0O0         2023                       43.0
                                       2024                       29.0
                          S0O1         2023                       41.0
                                       2024                       23.0
                          S0O1_ALLOC   2023                       43.0
...                                                                ...
MLP32_A010_LABEL_SHUFFLED S0O1_SUPPORT 2024                       36.0
                          S1O0         2023                       40.0
                                       2024                       55.0
                          S1O1         2023                       39.0
                                       2024                       40.0

[96 rows x 4 columns]