# Issue #394 — frozen 50/50 corrected-N7 full-history extension

Contract: `BJ-UNIFIED-N7-MIXED-FULL-HISTORY-001/v1`

Decision: `NO_MIXED_N7_EXTENSION_INCREMENT`. 2022-2024 parity + 2025-2026 extension evidence; no promotion.

In [1]:
from pathlib import Path
import json, pandas as pd
OUT=Path.cwd()/'results/n7_mixed_full_history'
decision=json.loads((OUT/'decision.json').read_text())
decision

{'consumes_218': False,
 'contract': 'BJ-UNIFIED-N7-MIXED-FULL-HISTORY-001/v1',
 'evidence_cutoff_ts': '2026-08-25T07:50:00Z',
 'exposed_historical_only': True,
 'failed_predicates': ['R3_2025_positive',
  'R3_extension_ex_largest_positive',
  'C1E3_extension_ex_largest_positive',
  'mixed_extension_ex_largest_positive',
  'no_annual_extension_year_reversal',
  'moving_block_p05_vs_r3_ext_nonnegative',
  'moving_block_p05_vs_c1e3_ext_nonnegative',
  'moving_block_p05_vs_r3_all_nonnegative',
  'moving_block_p05_vs_c1e3_all_nonnegative'],
 'predictates_report': {'C1E3_2025_positive': True,
  'C1E3_2026_positive': True,
  'C1E3_all_positive': True,
  'C1E3_extension_ex_largest_positive': False,
  'C1E3_extension_positive': True,
  'R3_2025_positive': False,
  'R3_2026_positive': True,
  'R3_all_positive': True,
  'R3_extension_ex_largest_positive': False,
  'R3_extension_positive': True,
  'diversification_not_mere_dilution': True,
  'extension_confirms_pre2025_c1e3': True,
  'extension_confirms_pre2025_r3': True,
  'extension_reverses_pre2025_c1e3': False,
  'extension_reverses_pre2025_r3': False,
  'extension_weakens_pre2025_r3': True,
  'mixed_all_ex_largest_positive': True,
  'mixed_all_positive': True,
  'mixed_extension_ex_largest_positive': False,
  'mixed_extension_positive': True,
  'mixed_maxdd_below_each_standalone': True,
  'moving_block_p05_vs_c1e3_all_nonnegative': False,
  'moving_block_p05_vs_c1e3_ext_nonnegative': False,
  'moving_block_p05_vs_r3_all_nonnegative': False,
  'moving_block_p05_vs_r3_ext_nonnegative': False,
  'no_annual_extension_year_reversal': False,
  'no_promotion_authorized': True,
  'r3_c1e3_correlation_below_one': True},
 'preserved_issues': [210, 218],
 'promotion_unlock_210': False,
 'prospective_authorized': False,
 'strategy_promoted': False,
 'verdict': 'NO_MIXED_N7_EXTENSION_INCREMENT'}

In [2]:
pd.read_csv(OUT/'performance.csv').query("denominator=='EXACT_COMMON'")

,denominator,scope,support_arm,schedule,issues,stake_cny,gross_cny,pnl_cny,ending_capital_cny,capital_return,...,max_drawdown_fraction,longest_profitable_issue_losing_run,losing_run_p90,max_underwater_issues,open_underwater_issues,terminal_underwater_issues,largest_payout_share,top5_payout_share,top10_payout_share,payout_hhi
56,EXACT_COMMON,2022,C1E3_SECONDARY,C1E3_STANDALONE,50,51200,40855.277515,-10344.722485,89655.277515,-0.103447,...,0.157041,11,8.9,42,42,42,0.259744,0.751503,0.984078,0.145250
57,EXACT_COMMON,2022,C1E3_SECONDARY,FRACTIONAL_50_50,50,25600,22033.084466,-3566.915534,96433.084466,-0.035669,...,0.079731,11,8.9,42,42,42,0.285413,0.791362,0.982504,0.163107
58,EXACT_COMMON,2022,C1E3_SECONDARY,MIXED_50_50,50,25600,20208.342864,-5391.657136,94608.342864,-0.053917,...,0.074886,11,6.2,42,42,42,0.262562,0.760788,0.983905,0.146498
59,EXACT_COMMON,2022,R0_CONTROL,R0_COMPARATOR,50,51200,36219.614590,-14980.385410,85019.614590,-0.149804,...,0.258720,18,14.5,50,50,50,0.364602,0.842767,1.000000,0.198984
60,EXACT_COMMON,2022,R3_CONTROL,FRACTIONAL_50_50,50,25600,10634.902426,-14965.097574,85034.902426,-0.149651,...,0.176441,19,18.7,50,50,50,0.328292,1.000000,1.000000,0.262652
61,EXACT_COMMON,2022,R3_CONTROL,MIXED_50_50,50,25600,10634.902426,-14965.097574,85034.902426,-0.149651,...,0.176441,19,18.7,50,50,50,0.328292,1.000000,1.000000,0.262652
62,EXACT_COMMON,2022,R3_CONTROL,R3_STANDALONE,50,51200,21269.804853,-29930.195147,70069.804853,-0.299302,...,0.352882,19,18.7,50,50,50,0.328292,1.000000,1.000000,0.262652
63,EXACT_COMMON,2023,C1E3_SECONDARY,C1E3_STANDALONE,47,48128,104090.606165,55962.606165,155962.606165,0.559626,...,0.090464,6,6.0,20,5,5,0.364966,0.813532,0.955460,0.212762
64,EXACT_COMMON,2023,C1E3_SECONDARY,FRACTIONAL_50_50,47,24064,46034.908188,21970.908188,121970.908188,0.219709,...,0.043650,6,6.0,18,5,5,0.326018,0.772684,0.953184,0.179257
65,EXACT_COMMON,2023,C1E3_SECONDARY,MIXED_50_50,47,24064,55387.766018,31323.766018,131323.766018,0.313238,...,0.047810,6,6.0,20,5,5,0.457256,0.835880,0.962459,0.257830
66,EXACT_COMMON,2023,R0_CONTROL,R0_COMPARATOR,47,48128,30862.657129,-17265.342871,82734.657129,-0.172653,...,0.279975,15,14.5,45,45,45,0.317831,0.864949,1.000000,0.186468
67,EXACT_COMMON,2023,R3_CONTROL,FRACTIONAL_50_50,47,24064,39829.559131,15765.559131,115765.559131,0.157656,...,0.107670,19,16.2,39,39,39,0.764989,0.994788,1.000000,0.604843
68,EXACT_COMMON,2023,R3_CONTROL,MIXED_50_50,47,24064,39829.559131,15765.559131,115765.559131,0.157656,...,0.107670,19,16.2,39,39,39,0.764989,0.994788,1.000000,0.604843
69,EXACT_COMMON,2023,R3_CONTROL,R3_STANDALONE,47,48128,79659.118262,31531.118262,131531.118262,0.315311,...,0.175187,19,16.2,39,39,39,0.764989,0.994788,1.000000,0.604843
70,EXACT_COMMON,2024,C1E3_SECONDARY,C1E3_STANDALONE,54,55296,55906.417195,610.417195,100610.417195,0.006104,...,0.114826,8,6.0,31,31,31,0.195762,0.554148,0.774917,0.087269
71,EXACT_COMMON,2024,C1E3_SECONDARY,FRACTIONAL_50_50,54,27648,27321.213187,-326.786813,99673.213187,-0.003268,...,0.061733,8,6.8,31,31,31,0.158254,0.529590,0.768155,0.080948
72,EXACT_COMMON,2024,C1E3_SECONDARY,MIXED_50_50,54,27648,27046.988644,-601.011356,99398.988644,-0.006010,...,0.072689,8,6.0,45,45,45,0.269761,0.586253,0.789582,0.113873
73,EXACT_COMMON,2024,R0_CONTROL,R0_COMPARATOR,54,55296,73811.789290,18515.789290,118515.789290,0.185158,...,0.108645,10,6.8,33,33,33,0.187388,0.584795,0.815713,0.095711
74,EXACT_COMMON,2024,R3_CONTROL,FRACTIONAL_50_50,54,27648,54183.238332,26535.238332,126535.238332,0.265352,...,0.049323,8,4.7,22,1,1,0.319762,0.686073,0.871480,0.148185
75,EXACT_COMMON,2024,R3_CONTROL,MIXED_50_50,54,27648,54183.238332,26535.238332,126535.238332,0.265352,...,0.049323,8,4.7,22,1,1,0.319762,0.686073,0.871480,0.148185
76,EXACT_COMMON,2024,R3_CONTROL,R3_STANDALONE,54,55296,108366.476664,53070.476664,153070.476664,0.530705,...,0.096271,8,4.7,22,1,1,0.319762,0.686073,0.871480,0.148185
77,EXACT_COMMON,2025,C1E3_SECONDARY,C1E3_STANDALONE,15,15360,16952.954007,1592.954007,101592.954007,0.015930,...,0.068565,7,6.4,10,4,4,0.788353,1.000000,1.000000,0.640966
78,EXACT_COMMON,2025,C1E3_SECONDARY,FRACTIONAL_50_50,15,7680,7163.546673,-516.453327,99483.546673,-0.005165,...,0.033844,8,7.2,8,4,4,0.737060,1.000000,1.000000,0.575803
79,EXACT_COMMON,2025,C1E3_SECONDARY,MIXED_50_50,15,7680,10908.711502,3228.711502,103228.711502,0.032287,...,0.034282,7,6.4,10,4,4,0.816773,1.000000,1.000000,0.681337
80,EXACT_COMMON,2025,R0_CONTROL,R0_COMPARATOR,15,15360,5610.858757,-9749.141243,90250.858757,-0.097491,...,0.114535,7,6.6,13,13,13,0.708067,1.000000,1.000000,0.586584
81,EXACT_COMMON,2025,R3_CONTROL,FRACTIONAL_50_50,15,7680,818.996218,-6861.003782,93138.996218,-0.068610,...,0.068610,9,8.6,15,15,15,1.000000,1.000000,1.000000,1.000000
82,EXACT_COMMON,2025,R3_CONTROL,MIXED_50_50,15,7680,818.996218,-6861.003782,93138.996218,-0.068610,...,0.068610,9,8.6,15,15,15,1.000000,1.000000,1.000000,1.000000
83,EXACT_COMMON,2025,R3_CONTROL,R3_STANDALONE,15,15360,1637.992436,-13722.007564,86277.992436,-0.137220,...,0.137220,9,8.6,15,15,15,1.000000,1.000000,1.000000,1.000000
84,EXACT_COMMON,2026,C1E3_SECONDARY,C1E3_STANDALONE,61,62464,73054.078029,10590.078029,110590.078029,0.105901,...,0.144321,7,7.0,31,0,0,0.192998,0.565122,0.790505,0.087783
85,EXACT_COMMON,2026,C1E3_SECONDARY,FRACTIONAL_50_50,61,31232,33229.445438,1997.445438,101997.445438,0.019974,...,0.066519,7,5.5,31,0,0,0.167625,0.524145,0.757985,0.078046
86,EXACT_COMMON,2026,C1E3_SECONDARY,MIXED_50_50,61,31232,33709.542129,2477.542129,102477.542129,0.024775,...,0.071568,7,7.0,27,23,23,0.167744,0.544868,0.785569,0.083265
87,EXACT_COMMON,2026,R0_CONTROL,R0_COMPARATOR,61,62464,111527.742167,49063.742167,149063.742167,0.490637,...,0.089778,11,8.3,24,0,0,0.189731,0.572651,0.835199,0.098149
88,EXACT_COMMON,2026,R3_CONTROL,FRACTIONAL_50_50,61,31232,40102.984406,8870.984406,108870.984406,0.088710,...,0.070979,14,11.6,32,0,0,0.234385,0.682782,0.940928,0.121644
89,EXACT_COMMON,2026,R3_CONTROL,MIXED_50_50,61,31232,40102.984406,8870.984406,108870.984406,0.088710,...,0.070979,14,11.6,32,0,0,0.234385,0.682782,0.940928,0.121644
90,EXACT_COMMON,2026,R3_CONTROL,R3_STANDALONE,61,62464,80205.968811,17741.968811,117741.968811,0.177420,...,0.140585,14,11.6,32,0,0,0.234385,0.682782,0.940928,0.121644
91,EXACT_COMMON,PRE_2025,C1E3_SECONDARY,C1E3_STANDALONE,151,154624,200852.300875,46228.300875,146228.300875,0.462283,...,0.208201,11,6.0,62,31,31,0.189142,0.475594,0.625629,0.069914
92,EXACT_COMMON,PRE_2025,C1E3_SECONDARY,FRACTIONAL_50_50,151,77312,95389.205840,18077.205840,118077.205840,0.180772,...,0.089051,11,6.9,62,31,31,0.157337,0.417595,0.604005,0.057092
93,EXACT_COMMON,PRE_2025,C1E3_SECONDARY,MIXED_50_50,151,77312,102643.097527,25331.097527,125331.097527,0.253311,...,0.104080,11,6.0,62,45,45,0.246742,0.521643,0.667811,0.088661
94,EXACT_COMMON,PRE_2025,R0_CONTROL,R0_COMPARATOR,151,154624,140894.061009,-13729.938991,86270.061009,-0.137299,...,0.419608,18,14.0,151,151,151,0.098169,0.393561,0.583649,0.048365
95,EXACT_COMMON,PRE_2025,R3_CONTROL,FRACTIONAL_50_50,151,77312,104647.699889,27335.699889,127335.699889,0.273357,...,0.176441,19,18.0,76,1,1,0.291160,0.621215,0.777060,0.130057
96,EXACT_COMMON,PRE_2025,R3_CONTROL,MIXED_50_50,151,77312,104647.699889,27335.699889,127335.699889,0.273357,...,0.176441,19,18.0,76,1,1,0.291160,0.621215,0.777060,0.130057
97,EXACT_COMMON,PRE_2025,R3_CONTROL,R3_STANDALONE,151,154624,209295.399779,54671.399779,154671.399779,0.546714,...,0.352882,19,18.0,76,1,1,0.291160,0.621215,0.777060,0.130057
98,EXACT_COMMON,EXTENSION_2025_2026,C1E3_SECONDARY,C1E3_STANDALONE,76,77824,90007.032036,12183.032036,112183.032036,0.121830,...,0.172876,7,7.0,41,0,0,0.156647,0.544896,0.758994,0.080568
99,EXACT_COMMON,EXTENSION_2025_2026,C1E3_SECONDARY,FRACTIONAL_50_50,76,38912,40392.992111,1480.992111,101480.992111,0.014810,...,0.083178,8,6.2,65,65,65,0.137898,0.503140,0.726815,0.070928
100,EXACT_COMMON,EXTENSION_2025_2026,C1E3_SECONDARY,MIXED_50_50,76,38912,44618.253631,5706.253631,105706.253631,0.057063,...,0.086110,7,7.0,40,23,23,0.199693,0.558378,0.771892,0.088255
101,EXACT_COMMON,EXTENSION_2025_2026,R0_CONTROL,R0_COMPARATOR,76,77824,117138.600924,39314.600924,139314.600924,0.393146,...,0.173464,11,7.8,24,0,0,0.180643,0.545221,0.795194,0.090317
102,EXACT_COMMON,EXTENSION_2025_2026,R3_CONTROL,FRACTIONAL_50_50,76,38912,40921.980624,2009.980624,102009.980624,0.020100,...,0.130420,14,11.0,75,0,0,0.229694,0.669117,0.922097,0.117224
103,EXACT_COMMON,EXTENSION_2025_2026,R3_CONTROL,MIXED_50_50,76,38912,40921.980624,2009.980624,102009.980624,0.020100,...,0.130420,14,11.0,75,0,0,0.229694,0.669117,0.922097,0.117224
104,EXACT_COMMON,EXTENSION_2025_2026,R3_CONTROL,R3_STANDALONE,76,77824,81843.961248,4019.961248,104019.961248,0.040200,...,0.260840,14,11.0,75,0,0,0.229694,0.669117,0.922097,0.117224
105,EXACT_COMMON,ALL,C1E3_SECONDARY,C1E3_STANDALONE,227,232448,290859.332911,58411.332911,158411.332911,0.584113,...,0.208201,11,7.0,107,107,107,0.130611,0.349004,0.499083,0.041054
106,EXACT_COMMON,ALL,C1E3_SECONDARY,FRACTIONAL_50_50,227,116224,135782.197951,19558.197951,119558.197951,0.195582,...,0.098055,11,7.0,107,107,107,0.110532,0.309820,0.457476,0.034454
107,EXACT_COMMON,ALL,C1E3_SECONDARY,MIXED_50_50,227,116224,147261.351158,31037.351158,131037.351158,0.310374,...,0.104080,11,7.0,121,121,121,0.171982,0.388066,0.539005,0.051176
108,EXACT_COMMON,ALL,R0_CONTROL,R0_COMPARATOR,227,232448,258032.661933,25584.661933,125584.661933,0.255847,...,0.419608,18,11.0,200,0,0,0.082006,0.305530,0.462410,0.033033
109,EXACT_COMMON,ALL,R3_CONTROL,FRACTIONAL_50_50,227,116224,145569.680513,29345.680513,129345.680513,0.293457,...,0.176441,19,17.0,76,0,0,0.209310,0.479740,0.636487,0.076476
110,EXACT_COMMON,ALL,R3_CONTROL,MIXED_50_50,227,116224,145569.680513,29345.680513,129345.680513,0.293457,...,0.176441,19,17.0,76,0,0,0.209310,0.479740,0.636487,0.076476
111,EXACT_COMMON,ALL,R3_CONTROL,R3_STANDALONE,227,232448,291139.361026,58691.361026,158691.361026,0.586914,...,0.352882,19,17.0,76,0,0,0.209310,0.479740,0.636487,0.076476

In [3]:
pd.read_csv(OUT/'performance.csv').query("denominator=='NATIVE'")

,denominator,scope,support_arm,schedule,issues,stake_cny,gross_cny,pnl_cny,ending_capital_cny,capital_return,...,max_drawdown_fraction,longest_profitable_issue_losing_run,losing_run_p90,max_underwater_issues,open_underwater_issues,terminal_underwater_issues,largest_payout_share,top5_payout_share,top10_payout_share,payout_hhi
0,NATIVE,2022,C1E3_SECONDARY,C1E3_STANDALONE,50,51200,40855.277515,-10344.722485,89655.277515,-0.103447,...,0.157041,11,8.9,42,42,42,0.259744,0.751503,0.984078,0.145250
1,NATIVE,2022,C1E3_SECONDARY,FRACTIONAL_50_50,50,25600,22033.084466,-3566.915534,96433.084466,-0.035669,...,0.079731,11,8.9,42,42,42,0.285413,0.791362,0.982504,0.163107
2,NATIVE,2022,C1E3_SECONDARY,MIXED_50_50,50,25600,20208.342864,-5391.657136,94608.342864,-0.053917,...,0.074886,11,6.2,42,42,42,0.262562,0.760788,0.983905,0.146498
3,NATIVE,2022,R0_CONTROL,R0_COMPARATOR,50,51200,36219.614590,-14980.385410,85019.614590,-0.149804,...,0.258720,18,14.5,50,50,50,0.364602,0.842767,1.000000,0.198984
4,NATIVE,2022,R3_CONTROL,FRACTIONAL_50_50,50,25600,10634.902426,-14965.097574,85034.902426,-0.149651,...,0.176441,19,18.7,50,50,50,0.328292,1.000000,1.000000,0.262652
5,NATIVE,2022,R3_CONTROL,MIXED_50_50,50,25600,10634.902426,-14965.097574,85034.902426,-0.149651,...,0.176441,19,18.7,50,50,50,0.328292,1.000000,1.000000,0.262652
6,NATIVE,2022,R3_CONTROL,R3_STANDALONE,50,51200,21269.804853,-29930.195147,70069.804853,-0.299302,...,0.352882,19,18.7,50,50,50,0.328292,1.000000,1.000000,0.262652
7,NATIVE,2023,C1E3_SECONDARY,C1E3_STANDALONE,47,48128,104090.606165,55962.606165,155962.606165,0.559626,...,0.090464,6,6.0,20,5,5,0.364966,0.813532,0.955460,0.212762
8,NATIVE,2023,C1E3_SECONDARY,FRACTIONAL_50_50,47,24064,46034.908188,21970.908188,121970.908188,0.219709,...,0.043650,6,6.0,18,5,5,0.326018,0.772684,0.953184,0.179257
9,NATIVE,2023,C1E3_SECONDARY,MIXED_50_50,47,24064,55387.766018,31323.766018,131323.766018,0.313238,...,0.047810,6,6.0,20,5,5,0.457256,0.835880,0.962459,0.257830
10,NATIVE,2023,R0_CONTROL,R0_COMPARATOR,47,48128,30862.657129,-17265.342871,82734.657129,-0.172653,...,0.279975,15,14.5,45,45,45,0.317831,0.864949,1.000000,0.186468
11,NATIVE,2023,R3_CONTROL,FRACTIONAL_50_50,47,24064,39829.559131,15765.559131,115765.559131,0.157656,...,0.107670,19,16.2,39,39,39,0.764989,0.994788,1.000000,0.604843
12,NATIVE,2023,R3_CONTROL,MIXED_50_50,47,24064,39829.559131,15765.559131,115765.559131,0.157656,...,0.107670,19,16.2,39,39,39,0.764989,0.994788,1.000000,0.604843
13,NATIVE,2023,R3_CONTROL,R3_STANDALONE,47,48128,79659.118262,31531.118262,131531.118262,0.315311,...,0.175187,19,16.2,39,39,39,0.764989,0.994788,1.000000,0.604843
14,NATIVE,2024,C1E3_SECONDARY,C1E3_STANDALONE,54,55296,55906.417195,610.417195,100610.417195,0.006104,...,0.114826,8,6.0,31,31,31,0.195762,0.554148,0.774917,0.087269
15,NATIVE,2024,C1E3_SECONDARY,FRACTIONAL_50_50,54,27648,27321.213187,-326.786813,99673.213187,-0.003268,...,0.061733,8,6.8,31,31,31,0.158254,0.529590,0.768155,0.080948
16,NATIVE,2024,C1E3_SECONDARY,MIXED_50_50,54,27648,27046.988644,-601.011356,99398.988644,-0.006010,...,0.072689,8,6.0,45,45,45,0.269761,0.586253,0.789582,0.113873
17,NATIVE,2024,R0_CONTROL,R0_COMPARATOR,54,55296,73811.789290,18515.789290,118515.789290,0.185158,...,0.108645,10,6.8,33,33,33,0.187388,0.584795,0.815713,0.095711
18,NATIVE,2024,R3_CONTROL,FRACTIONAL_50_50,54,27648,54183.238332,26535.238332,126535.238332,0.265352,...,0.049323,8,4.7,22,1,1,0.319762,0.686073,0.871480,0.148185
19,NATIVE,2024,R3_CONTROL,MIXED_50_50,54,27648,54183.238332,26535.238332,126535.238332,0.265352,...,0.049323,8,4.7,22,1,1,0.319762,0.686073,0.871480,0.148185
20,NATIVE,2024,R3_CONTROL,R3_STANDALONE,54,55296,108366.476664,53070.476664,153070.476664,0.530705,...,0.096271,8,4.7,22,1,1,0.319762,0.686073,0.871480,0.148185
21,NATIVE,2025,C1E3_SECONDARY,C1E3_STANDALONE,15,15360,16952.954007,1592.954007,101592.954007,0.015930,...,0.068565,7,6.4,10,4,4,0.788353,1.000000,1.000000,0.640966
22,NATIVE,2025,C1E3_SECONDARY,FRACTIONAL_50_50,15,7680,7163.546673,-516.453327,99483.546673,-0.005165,...,0.033844,8,7.2,8,4,4,0.737060,1.000000,1.000000,0.575803
23,NATIVE,2025,C1E3_SECONDARY,MIXED_50_50,15,7680,10908.711502,3228.711502,103228.711502,0.032287,...,0.034282,7,6.4,10,4,4,0.816773,1.000000,1.000000,0.681337
24,NATIVE,2025,R0_CONTROL,R0_COMPARATOR,15,15360,5610.858757,-9749.141243,90250.858757,-0.097491,...,0.114535,7,6.6,13,13,13,0.708067,1.000000,1.000000,0.586584
25,NATIVE,2025,R3_CONTROL,FRACTIONAL_50_50,15,7680,818.996218,-6861.003782,93138.996218,-0.068610,...,0.068610,9,8.6,15,15,15,1.000000,1.000000,1.000000,1.000000
26,NATIVE,2025,R3_CONTROL,MIXED_50_50,15,7680,818.996218,-6861.003782,93138.996218,-0.068610,...,0.068610,9,8.6,15,15,15,1.000000,1.000000,1.000000,1.000000
27,NATIVE,2025,R3_CONTROL,R3_STANDALONE,15,15360,1637.992436,-13722.007564,86277.992436,-0.137220,...,0.137220,9,8.6,15,15,15,1.000000,1.000000,1.000000,1.000000
28,NATIVE,2026,C1E3_SECONDARY,C1E3_STANDALONE,61,62464,73054.078029,10590.078029,110590.078029,0.105901,...,0.144321,7,7.0,31,0,0,0.192998,0.565122,0.790505,0.087783
29,NATIVE,2026,C1E3_SECONDARY,FRACTIONAL_50_50,61,31232,33229.445438,1997.445438,101997.445438,0.019974,...,0.066519,7,5.5,31,0,0,0.167625,0.524145,0.757985,0.078046
30,NATIVE,2026,C1E3_SECONDARY,MIXED_50_50,61,31232,33709.542129,2477.542129,102477.542129,0.024775,...,0.071568,7,7.0,27,23,23,0.167744,0.544868,0.785569,0.083265
31,NATIVE,2026,R0_CONTROL,R0_COMPARATOR,61,62464,111527.742167,49063.742167,149063.742167,0.490637,...,0.089778,11,8.3,24,0,0,0.189731,0.572651,0.835199,0.098149
32,NATIVE,2026,R3_CONTROL,FRACTIONAL_50_50,61,31232,40102.984406,8870.984406,108870.984406,0.088710,...,0.070979,14,11.6,32,0,0,0.234385,0.682782,0.940928,0.121644
33,NATIVE,2026,R3_CONTROL,MIXED_50_50,61,31232,40102.984406,8870.984406,108870.984406,0.088710,...,0.070979,14,11.6,32,0,0,0.234385,0.682782,0.940928,0.121644
34,NATIVE,2026,R3_CONTROL,R3_STANDALONE,61,62464,80205.968811,17741.968811,117741.968811,0.177420,...,0.140585,14,11.6,32,0,0,0.234385,0.682782,0.940928,0.121644
35,NATIVE,PRE_2025,C1E3_SECONDARY,C1E3_STANDALONE,151,154624,200852.300875,46228.300875,146228.300875,0.462283,...,0.208201,11,6.0,62,31,31,0.189142,0.475594,0.625629,0.069914
36,NATIVE,PRE_2025,C1E3_SECONDARY,FRACTIONAL_50_50,151,77312,95389.205840,18077.205840,118077.205840,0.180772,...,0.089051,11,6.9,62,31,31,0.157337,0.417595,0.604005,0.057092
37,NATIVE,PRE_2025,C1E3_SECONDARY,MIXED_50_50,151,77312,102643.097527,25331.097527,125331.097527,0.253311,...,0.104080,11,6.0,62,45,45,0.246742,0.521643,0.667811,0.088661
38,NATIVE,PRE_2025,R0_CONTROL,R0_COMPARATOR,151,154624,140894.061009,-13729.938991,86270.061009,-0.137299,...,0.419608,18,14.0,151,151,151,0.098169,0.393561,0.583649,0.048365
39,NATIVE,PRE_2025,R3_CONTROL,FRACTIONAL_50_50,151,77312,104647.699889,27335.699889,127335.699889,0.273357,...,0.176441,19,18.0,76,1,1,0.291160,0.621215,0.777060,0.130057
40,NATIVE,PRE_2025,R3_CONTROL,MIXED_50_50,151,77312,104647.699889,27335.699889,127335.699889,0.273357,...,0.176441,19,18.0,76,1,1,0.291160,0.621215,0.777060,0.130057
41,NATIVE,PRE_2025,R3_CONTROL,R3_STANDALONE,151,154624,209295.399779,54671.399779,154671.399779,0.546714,...,0.352882,19,18.0,76,1,1,0.291160,0.621215,0.777060,0.130057
42,NATIVE,EXTENSION_2025_2026,C1E3_SECONDARY,C1E3_STANDALONE,76,77824,90007.032036,12183.032036,112183.032036,0.121830,...,0.172876,7,7.0,41,0,0,0.156647,0.544896,0.758994,0.080568
43,NATIVE,EXTENSION_2025_2026,C1E3_SECONDARY,FRACTIONAL_50_50,76,38912,40392.992111,1480.992111,101480.992111,0.014810,...,0.083178,8,6.2,65,65,65,0.137898,0.503140,0.726815,0.070928
44,NATIVE,EXTENSION_2025_2026,C1E3_SECONDARY,MIXED_50_50,76,38912,44618.253631,5706.253631,105706.253631,0.057063,...,0.086110,7,7.0,40,23,23,0.199693,0.558378,0.771892,0.088255
45,NATIVE,EXTENSION_2025_2026,R0_CONTROL,R0_COMPARATOR,76,77824,117138.600924,39314.600924,139314.600924,0.393146,...,0.173464,11,7.8,24,0,0,0.180643,0.545221,0.795194,0.090317
46,NATIVE,EXTENSION_2025_2026,R3_CONTROL,FRACTIONAL_50_50,76,38912,40921.980624,2009.980624,102009.980624,0.020100,...,0.130420,14,11.0,75,0,0,0.229694,0.669117,0.922097,0.117224
47,NATIVE,EXTENSION_2025_2026,R3_CONTROL,MIXED_50_50,76,38912,40921.980624,2009.980624,102009.980624,0.020100,...,0.130420,14,11.0,75,0,0,0.229694,0.669117,0.922097,0.117224
48,NATIVE,EXTENSION_2025_2026,R3_CONTROL,R3_STANDALONE,76,77824,81843.961248,4019.961248,104019.961248,0.040200,...,0.260840,14,11.0,75,0,0,0.229694,0.669117,0.922097,0.117224
49,NATIVE,ALL,C1E3_SECONDARY,C1E3_STANDALONE,227,232448,290859.332911,58411.332911,158411.332911,0.584113,...,0.208201,11,7.0,107,107,107,0.130611,0.349004,0.499083,0.041054
50,NATIVE,ALL,C1E3_SECONDARY,FRACTIONAL_50_50,227,116224,135782.197951,19558.197951,119558.197951,0.195582,...,0.098055,11,7.0,107,107,107,0.110532,0.309820,0.457476,0.034454
51,NATIVE,ALL,C1E3_SECONDARY,MIXED_50_50,227,116224,147261.351158,31037.351158,131037.351158,0.310374,...,0.104080,11,7.0,121,121,121,0.171982,0.388066,0.539005,0.051176
52,NATIVE,ALL,R0_CONTROL,R0_COMPARATOR,227,232448,258032.661933,25584.661933,125584.661933,0.255847,...,0.419608,18,11.0,200,0,0,0.082006,0.305530,0.462410,0.033033
53,NATIVE,ALL,R3_CONTROL,FRACTIONAL_50_50,227,116224,145569.680513,29345.680513,129345.680513,0.293457,...,0.176441,19,17.0,76,0,0,0.209310,0.479740,0.636487,0.076476
54,NATIVE,ALL,R3_CONTROL,MIXED_50_50,227,116224,145569.680513,29345.680513,129345.680513,0.293457,...,0.176441,19,17.0,76,0,0,0.209310,0.479740,0.636487,0.076476
55,NATIVE,ALL,R3_CONTROL,R3_STANDALONE,227,232448,291139.361026,58691.361026,158691.361026,0.586914,...,0.352882,19,17.0,76,0,0,0.209310,0.479740,0.636487,0.076476

In [4]:
pd.read_csv(OUT/'matched_contrasts.csv')

,scope,subject_schedule,reference_schedule,contrast,issues,subject_pnl_cny,reference_pnl_cny,matched_lift_cny,matched_ex_largest_lift_cny,largest_abs_paired_delta_cny,moving_block_p05_lift_cny
0,PRE_2025,MIXED_50_50,R3_STANDALONE,vs_R3,151,52666.797417,54671.399779,-2004.602362,28464.588693,30469.191055,-581.646123
1,PRE_2025,MIXED_50_50,C1E3_STANDALONE,vs_C1E3,151,52666.797417,46228.300875,6438.496541,-24030.694514,30469.191055,-440.122088
2,PRE_2025,MIXED_50_50,R0_COMPARATOR,vs_R0,151,52666.797417,-13729.938991,66396.736408,35927.545352,30469.191055,-82.082163
3,EXTENSION_2025_2026,MIXED_50_50,R3_STANDALONE,vs_R3,76,7716.234255,4019.961248,3696.273007,-5213.668767,8909.941774,-252.403486
4,EXTENSION_2025_2026,MIXED_50_50,C1E3_STANDALONE,vs_C1E3,76,7716.234255,12183.032036,-4466.797781,-9514.871040,5048.073259,-265.114667
5,EXTENSION_2025_2026,MIXED_50_50,R0_COMPARATOR,vs_R0,76,7716.234255,39314.600924,-31598.366669,-10438.129952,21160.236717,-1116.442302
6,ALL,MIXED_50_50,R3_STANDALONE,vs_R3,227,60383.031671,58691.361026,1691.670645,32160.861700,30469.191055,-361.164598
7,ALL,MIXED_50_50,C1E3_STANDALONE,vs_C1E3,227,60383.031671,58411.332911,1971.698760,-28497.492296,30469.191055,-315.232149
8,ALL,MIXED_50_50,R0_COMPARATOR,vs_R0,227,60383.031671,25584.661933,34798.369738,4329.178683,30469.191055,-287.192706

In [5]:
pd.read_csv(OUT/'correlations.csv')

,scope,issues,pearson_issue_pnl,spearman_issue_pnl,downside_issues,pearson_downside_pnl,simultaneous_profit_rate,simultaneous_loss_rate,underwater_state_overlap_rate,top5_payout_issue_overlap,top10_payout_issue_overlap
0,ALL,227,0.075713,0.376948,203,-0.04179,0.105727,0.69163,0.9163,0.2,0.2

In [6]:
pd.read_csv(OUT/'integer_fractional_reconciliation.csv')

,scope,issues,integer_stake_cny,fractional_stake_cny,integer_pnl_cny,fractional_pnl_cny,integer_roi,fractional_roi,integer_r3_pnl_cny,fractional_r3_pnl_cny,integer_c1e3_pnl_cny,fractional_c1e3_pnl_cny,integer_unit_effect_pnl_cny
0,PRE_2025,151,154624,154624,52666.797417,45412.905730,0.340612,0.293699,27335.699889,27335.699889,25331.097527,18077.205840,7253.891687
1,EXTENSION_2025_2026,76,77824,77824,7716.234255,3490.972735,0.099150,0.044857,2009.980624,2009.980624,5706.253631,1480.992111,4225.261520
2,ALL,227,232448,232448,60383.031671,48903.878464,0.259770,0.210386,29345.680513,29345.680513,31037.351158,19558.197951,11479.153207

In [7]:
pd.read_csv(OUT/'decision_gates.csv')

                                        gate  passed
0                           R3_2025_positive   False
1                         C1E3_2025_positive    True
2                           R3_2026_positive    True
3                         C1E3_2026_positive    True
4                      R3_extension_positive    True
5                    C1E3_extension_positive    True
6                            R3_all_positive    True
7                          C1E3_all_positive    True
8           R3_extension_ex_largest_positive   False
9         C1E3_extension_ex_largest_positive   False
10                  mixed_extension_positive    True
11                        mixed_all_positive    True
12       mixed_extension_ex_largest_positive   False
13             mixed_all_ex_largest_positive    True
14         mixed_maxdd_below_each_standalone    True
15             r3_c1e3_correlation_below_one    True
16         diversification_not_mere_dilution    True
17         no_annual_extension_year_reversal   False
18    moving_block_p05_vs_r3_ext_nonnegative   False
19  moving_block_p05_vs_c1e3_ext_nonnegative   False
20    moving_block_p05_vs_r3_all_nonnegative   False
21  moving_block_p05_vs_c1e3_all_nonnegative   False
22             extension_confirms_pre2025_r3    True
23              extension_weakens_pre2025_r3    True
24             extension_reverses_pre2025_r3   False
25           extension_confirms_pre2025_c1e3    True
26           extension_reverses_pre2025_c1e3   False
27                   no_promotion_authorized    True

In [8]:
pd.read_csv(OUT/'issue_ledger.csv').head(40)

,issue,issue_year,inclusion_status,reason,panel_fixtures,supported_fixtures
0,22011,2022,EXCLUDED,CORE_EXCLUDED_SETTLEMENT_INCOMPLETE,63,63
1,22012,2022,EXCLUDED,CORE_EXCLUDED_SETTLEMENT_INCOMPLETE,182,182
2,22013,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,218,218
3,22014,2022,EXCLUDED,CORE_EXCLUDED_SETTLEMENT_INCOMPLETE,293,293
4,22015,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,148,148
5,22021,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,376,376
6,22022,2022,EXCLUDED,CORE_EXCLUDED_SETTLEMENT_INCOMPLETE,418,418
7,22023,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,430,430
8,22031,2022,EXCLUDED,CORE_EXCLUDED_SETTLEMENT_INCOMPLETE,500,500
9,22032,2022,EXCLUDED,CORE_EXCLUDED_SETTLEMENT_INCOMPLETE,409,409
10,22033,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,447,447
11,22034,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,137,137
12,22035,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,66,66
13,22041,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,396,396
14,22042,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,498,498
15,22043,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,472,472
16,22044,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,522,522
17,22045,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,80,80
18,22051,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,376,376
19,22052,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,472,472
20,22053,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,435,435
21,22054,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,362,362
22,22055,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,230,230
23,22061,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,151,151
24,22062,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,149,149
25,22063,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,167,167
26,22064,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,174,174
27,22065,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,39,39
28,22071,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,161,161
29,22072,2022,EXCLUDED,CORE_EXCLUDED_SETTLEMENT_INCOMPLETE,209,209
30,22073,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,239,239
31,22074,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,273,273
32,22075,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,50,50
33,22081,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,294,294
34,22082,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,464,464
35,22083,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,509,509
36,22084,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,501,501
37,22085,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,496,496
38,22091,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,567,567
39,22092,2022,INCLUDED,INCLUDED_TRUSTED_SETTLEMENT_COMPLETE,457,457

All outcomes are exposed historical evidence: 2022-2024 parity and 2025-2026 retrospective extension. The notebook does not authorize promotion.