# Issue #394 — frozen 50/50 corrected-N7 full-history extension

Contract: `BJ-UNIFIED-N7-MIXED-FULL-HISTORY-001/v1`

Decision: `NO_MIXED_N7_EXTENSION_INCREMENT`. 2022-2024 parity + 2025-2026 extension evidence; no promotion.

In [1]:
from pathlib import Path
import json, pandas as pd
OUT=Path.cwd()/'results/n7_mixed_full_history'
decision=json.loads((OUT/'decision.json').read_text())
decision

{'consumes_218': False,
 'contract': 'BJ-UNIFIED-N7-MIXED-FULL-HISTORY-001/v1',
 'evidence_cutoff_ts': '2026-08-25T14:10:00Z',
 'exposed_historical_only': True,
 'failed_predicates': ['R3_2025_positive',
  'C1E3_2025_positive',
  'R3_extension_positive',
  'R3_extension_ex_largest_positive',
  'C1E3_extension_ex_largest_positive',
  'mixed_extension_positive',
  'mixed_extension_ex_largest_positive',
  'mixed_maxdd_below_each_standalone',
  'diversification_not_mere_dilution',
  'no_annual_extension_year_reversal',
  'moving_block_p05_vs_r3_ext_nonnegative',
  'moving_block_p05_vs_c1e3_ext_nonnegative',
  'moving_block_p05_vs_r3_all_nonnegative',
  'moving_block_p05_vs_c1e3_all_nonnegative',
  'extension_confirms_pre2025_r3'],
 'predictates_report': {'C1E3_2025_positive': False,
  'C1E3_2026_positive': True,
  'C1E3_all_positive': True,
  'C1E3_extension_ex_largest_positive': False,
  'C1E3_extension_positive': True,
  'R3_2025_positive': False,
  'R3_2026_positive': True,
  'R3_all_positive': True,
  'R3_extension_ex_largest_positive': False,
  'R3_extension_positive': False,
  'diversification_not_mere_dilution': False,
  'extension_confirms_pre2025_c1e3': True,
  'extension_confirms_pre2025_r3': False,
  'extension_reverses_pre2025_c1e3': False,
  'extension_reverses_pre2025_r3': True,
  'extension_weakens_pre2025_r3': True,
  'mixed_all_ex_largest_positive': True,
  'mixed_all_positive': True,
  'mixed_extension_ex_largest_positive': False,
  'mixed_extension_positive': False,
  'mixed_maxdd_below_each_standalone': False,
  'moving_block_p05_vs_c1e3_all_nonnegative': False,
  'moving_block_p05_vs_c1e3_ext_nonnegative': False,
  'moving_block_p05_vs_r3_all_nonnegative': False,
  'moving_block_p05_vs_r3_ext_nonnegative': False,
  'no_annual_extension_year_reversal': False,
  'no_promotion_authorized': True,
  'r3_c1e3_correlation_below_one': True},
 'preserved_issues': [210, 218],
 'promotion_unlock_210': False,
 'prospective_authorized': False,
 'strategy_promoted': False,
 'verdict': 'NO_MIXED_N7_EXTENSION_INCREMENT'}

In [2]:
pd.read_csv(OUT/'performance.csv').query("denominator=='EXACT_COMMON'")

,denominator,scope,support_arm,schedule,issues,stake_cny,gross_cny,pnl_cny,ending_capital_cny,capital_return,...,max_drawdown_fraction,longest_profitable_issue_losing_run,losing_run_p90,max_underwater_issues,open_underwater_issues,terminal_underwater_issues,largest_payout_share,top5_payout_share,top10_payout_share,payout_hhi
40,EXACT_COMMON,2022,C1E3_SECONDARY,C1E3_STANDALONE,50,51200,40855.277515,-10344.722485,89655.277515,-0.103447,...,0.157041,11,8.9,42,42,42,0.259744,0.751503,0.984078,0.145250
41,EXACT_COMMON,2022,PORTFOLIO,FRACTIONAL_50_50,50,51200,32667.986892,-18532.013108,81467.986892,-0.185320,...,0.210032,7,5.4,50,50,50,0.192498,0.718937,0.964727,0.122840
42,EXACT_COMMON,2022,PORTFOLIO,MIXED_50_50,50,51200,30843.245291,-20356.754709,79643.245291,-0.203568,...,0.226262,7,5.4,50,50,50,0.172030,0.673140,0.947501,0.113811
43,EXACT_COMMON,2022,R0_CONTROL,R0_COMPARATOR,50,51200,36219.614590,-14980.385410,85019.614590,-0.149804,...,0.258720,18,14.5,50,50,50,0.364602,0.842767,1.000000,0.198984
44,EXACT_COMMON,2022,R3_CONTROL,R3_STANDALONE,50,51200,21269.804853,-29930.195147,70069.804853,-0.299302,...,0.352882,19,18.7,50,50,50,0.328292,1.000000,1.000000,0.262652
45,EXACT_COMMON,2023,C1E3_SECONDARY,C1E3_STANDALONE,47,48128,104090.606165,55962.606165,155962.606165,0.559626,...,0.090464,6,6.0,20,5,5,0.364966,0.813532,0.955460,0.212762
46,EXACT_COMMON,2023,PORTFOLIO,FRACTIONAL_50_50,47,48128,85864.467319,37736.467319,137736.467319,0.377365,...,0.061352,8,6.0,17,5,5,0.354852,0.779990,0.937748,0.185382
47,EXACT_COMMON,2023,PORTFOLIO,MIXED_50_50,47,48128,95217.325149,47089.325149,147089.325149,0.470893,...,0.065653,9,6.3,17,5,5,0.319996,0.822004,0.949039,0.195638
48,EXACT_COMMON,2023,R0_CONTROL,R0_COMPARATOR,47,48128,30862.657129,-17265.342871,82734.657129,-0.172653,...,0.279975,15,14.5,45,45,45,0.317831,0.864949,1.000000,0.186468
49,EXACT_COMMON,2023,R3_CONTROL,R3_STANDALONE,47,48128,79659.118262,31531.118262,131531.118262,0.315311,...,0.175187,19,16.2,39,39,39,0.764989,0.994788,1.000000,0.604843
50,EXACT_COMMON,2024,C1E3_SECONDARY,C1E3_STANDALONE,54,55296,55906.417195,610.417195,100610.417195,0.006104,...,0.114826,8,6.0,31,31,31,0.195762,0.554148,0.774917,0.087269
51,EXACT_COMMON,2024,PORTFOLIO,FRACTIONAL_50_50,54,55296,81504.451519,26208.451519,126208.451519,0.262085,...,0.102205,8,4.0,14,4,4,0.212574,0.555981,0.763439,0.091167
52,EXACT_COMMON,2024,PORTFOLIO,MIXED_50_50,54,55296,81230.226976,25934.226976,125934.226976,0.259342,...,0.102689,8,4.0,14,4,4,0.213292,0.570410,0.777943,0.092716
53,EXACT_COMMON,2024,R0_CONTROL,R0_COMPARATOR,54,55296,73811.789290,18515.789290,118515.789290,0.185158,...,0.108645,10,6.8,33,33,33,0.187388,0.584795,0.815713,0.095711
54,EXACT_COMMON,2024,R3_CONTROL,R3_STANDALONE,54,55296,108366.476664,53070.476664,153070.476664,0.530705,...,0.096271,8,4.7,22,1,1,0.319762,0.686073,0.871480,0.148185
55,EXACT_COMMON,2025,C1E3_SECONDARY,C1E3_STANDALONE,56,57344,49289.140194,-8054.859806,91945.140194,-0.080549,...,0.148013,17,8.0,27,27,27,0.268720,0.625001,0.866510,0.119129
56,EXACT_COMMON,2025,PORTFOLIO,FRACTIONAL_50_50,56,57344,40832.615121,-16511.384879,83488.615121,-0.165114,...,0.176896,9,7.0,56,56,56,0.136848,0.528751,0.752505,0.074936
57,EXACT_COMMON,2025,PORTFOLIO,MIXED_50_50,56,57344,44896.521740,-12447.478260,87552.521740,-0.124475,...,0.138001,11,9.2,45,45,45,0.196674,0.540733,0.787414,0.087531
58,EXACT_COMMON,2025,R0_CONTROL,R0_COMPARATOR,56,57344,38311.047101,-19032.952899,80967.047101,-0.190330,...,0.205206,14,11.2,54,54,54,0.288330,0.734212,0.945453,0.144465
59,EXACT_COMMON,2025,R3_CONTROL,R3_STANDALONE,56,57344,35298.003335,-22045.996665,77954.003335,-0.220460,...,0.277110,14,10.0,56,56,56,0.316609,0.779075,0.967586,0.163626
60,EXACT_COMMON,2026,C1E3_SECONDARY,C1E3_STANDALONE,61,62464,73054.078029,10590.078029,110590.078029,0.105901,...,0.144321,7,7.0,31,0,0,0.192998,0.565122,0.790505,0.087783
61,EXACT_COMMON,2026,PORTFOLIO,FRACTIONAL_50_50,61,62464,73332.429843,10868.429843,110868.429843,0.108684,...,0.121984,7,6.7,31,0,0,0.204134,0.516695,0.747957,0.083456
62,EXACT_COMMON,2026,PORTFOLIO,MIXED_50_50,61,62464,73812.526535,11348.526535,111348.526535,0.113485,...,0.125953,8,6.8,31,0,0,0.191015,0.514133,0.756249,0.080622
63,EXACT_COMMON,2026,R0_CONTROL,R0_COMPARATOR,61,62464,111527.742167,49063.742167,149063.742167,0.490637,...,0.089778,11,8.3,24,0,0,0.189731,0.572651,0.835199,0.098149
64,EXACT_COMMON,2026,R3_CONTROL,R3_STANDALONE,61,62464,80205.968811,17741.968811,117741.968811,0.177420,...,0.140585,14,11.6,32,0,0,0.234385,0.682782,0.940928,0.121644
65,EXACT_COMMON,PRE_2025,C1E3_SECONDARY,C1E3_STANDALONE,151,154624,200852.300875,46228.300875,146228.300875,0.462283,...,0.208201,11,6.0,62,31,31,0.189142,0.475594,0.625629,0.069914
66,EXACT_COMMON,PRE_2025,PORTFOLIO,FRACTIONAL_50_50,151,154624,200036.905730,45412.905730,145412.905730,0.454129,...,0.212721,8,6.0,54,4,4,0.152318,0.415555,0.572551,0.052568
67,EXACT_COMMON,PRE_2025,PORTFOLIO,MIXED_50_50,151,154624,207290.797417,52666.797417,152666.797417,0.526668,...,0.231725,9,7.0,54,4,4,0.146988,0.440394,0.601105,0.058036
68,EXACT_COMMON,PRE_2025,R0_CONTROL,R0_COMPARATOR,151,154624,140894.061009,-13729.938991,86270.061009,-0.137299,...,0.419608,18,14.0,151,151,151,0.098169,0.393561,0.583649,0.048365
69,EXACT_COMMON,PRE_2025,R3_CONTROL,R3_STANDALONE,151,154624,209295.399779,54671.399779,154671.399779,0.546714,...,0.352882,19,18.0,76,1,1,0.291160,0.621215,0.777060,0.130057
70,EXACT_COMMON,EXTENSION_2025_2026,C1E3_SECONDARY,C1E3_STANDALONE,117,119808,122343.218222,2535.218222,102535.218222,0.025352,...,0.276239,17,7.0,88,88,88,0.115244,0.399896,0.593918,0.050635
71,EXACT_COMMON,EXTENSION_2025_2026,PORTFOLIO,FRACTIONAL_50_50,117,119808,114165.044964,-5642.955036,94357.044964,-0.056430,...,0.277570,9,7.0,117,117,117,0.131123,0.342163,0.532055,0.044020
72,EXACT_COMMON,EXTENSION_2025_2026,PORTFOLIO,MIXED_50_50,117,119808,118709.048275,-1098.951725,98901.048275,-0.010990,...,0.244601,11,7.8,106,106,106,0.118772,0.348484,0.554145,0.043691
73,EXACT_COMMON,EXTENSION_2025_2026,R0_CONTROL,R0_COMPARATOR,117,119808,149838.789268,30030.789268,130030.789268,0.300308,...,0.264165,14,10.3,88,0,0,0.141220,0.451803,0.667504,0.063819
74,EXACT_COMMON,EXTENSION_2025_2026,R3_CONTROL,R3_STANDALONE,117,119808,115503.972146,-4304.027854,95695.972146,-0.043040,...,0.344080,14,11.9,117,117,117,0.162757,0.508414,0.746172,0.073937
75,EXACT_COMMON,ALL,C1E3_SECONDARY,C1E3_STANDALONE,268,274432,323195.519098,48763.519098,148763.519098,0.487635,...,0.217745,17,7.0,148,148,148,0.117544,0.313715,0.448778,0.034257
76,EXACT_COMMON,ALL,PORTFOLIO,FRACTIONAL_50_50,268,274432,314201.950694,39769.950694,139769.950694,0.397700,...,0.212721,9,7.0,121,121,121,0.096973,0.280631,0.398975,0.027119
77,EXACT_COMMON,ALL,PORTFOLIO,MIXED_50_50,268,274432,325999.845692,51567.845692,151567.845692,0.515678,...,0.231725,11,7.6,121,121,121,0.093464,0.297601,0.416714,0.029258
78,EXACT_COMMON,ALL,R0_CONTROL,R0_COMPARATOR,268,274432,290732.850277,16300.850277,116300.850277,0.163009,...,0.419608,18,11.6,242,0,0,0.072782,0.271166,0.425130,0.028310
79,EXACT_COMMON,ALL,R3_CONTROL,R3_STANDALONE,268,274432,324799.371925,50367.371925,150367.371925,0.503674,...,0.352882,19,14.9,118,118,118,0.187619,0.430023,0.581101,0.063354

In [3]:
pd.read_csv(OUT/'performance.csv').query("denominator=='NATIVE'")

,denominator,scope,support_arm,schedule,issues,stake_cny,gross_cny,pnl_cny,ending_capital_cny,capital_return,...,max_drawdown_fraction,longest_profitable_issue_losing_run,losing_run_p90,max_underwater_issues,open_underwater_issues,terminal_underwater_issues,largest_payout_share,top5_payout_share,top10_payout_share,payout_hhi
0,NATIVE,2022,C1E3_SECONDARY,C1E3_STANDALONE,50,51200,40855.277515,-10344.722485,89655.277515,-0.103447,...,0.157041,11,8.9,42,42,42,0.259744,0.751503,0.984078,0.145250
1,NATIVE,2022,PORTFOLIO,FRACTIONAL_50_50,50,51200,32667.986892,-18532.013108,81467.986892,-0.185320,...,0.210032,7,5.4,50,50,50,0.192498,0.718937,0.964727,0.122840
2,NATIVE,2022,PORTFOLIO,MIXED_50_50,50,51200,30843.245291,-20356.754709,79643.245291,-0.203568,...,0.226262,7,5.4,50,50,50,0.172030,0.673140,0.947501,0.113811
3,NATIVE,2022,R0_CONTROL,R0_COMPARATOR,50,51200,36219.614590,-14980.385410,85019.614590,-0.149804,...,0.258720,18,14.5,50,50,50,0.364602,0.842767,1.000000,0.198984
4,NATIVE,2022,R3_CONTROL,R3_STANDALONE,50,51200,21269.804853,-29930.195147,70069.804853,-0.299302,...,0.352882,19,18.7,50,50,50,0.328292,1.000000,1.000000,0.262652
5,NATIVE,2023,C1E3_SECONDARY,C1E3_STANDALONE,47,48128,104090.606165,55962.606165,155962.606165,0.559626,...,0.090464,6,6.0,20,5,5,0.364966,0.813532,0.955460,0.212762
6,NATIVE,2023,PORTFOLIO,FRACTIONAL_50_50,47,48128,85864.467319,37736.467319,137736.467319,0.377365,...,0.061352,8,6.0,17,5,5,0.354852,0.779990,0.937748,0.185382
7,NATIVE,2023,PORTFOLIO,MIXED_50_50,47,48128,95217.325149,47089.325149,147089.325149,0.470893,...,0.065653,9,6.3,17,5,5,0.319996,0.822004,0.949039,0.195638
8,NATIVE,2023,R0_CONTROL,R0_COMPARATOR,47,48128,30862.657129,-17265.342871,82734.657129,-0.172653,...,0.279975,15,14.5,45,45,45,0.317831,0.864949,1.000000,0.186468
9,NATIVE,2023,R3_CONTROL,R3_STANDALONE,47,48128,79659.118262,31531.118262,131531.118262,0.315311,...,0.175187,19,16.2,39,39,39,0.764989,0.994788,1.000000,0.604843
10,NATIVE,2024,C1E3_SECONDARY,C1E3_STANDALONE,54,55296,55906.417195,610.417195,100610.417195,0.006104,...,0.114826,8,6.0,31,31,31,0.195762,0.554148,0.774917,0.087269
11,NATIVE,2024,PORTFOLIO,FRACTIONAL_50_50,54,55296,81504.451519,26208.451519,126208.451519,0.262085,...,0.102205,8,4.0,14,4,4,0.212574,0.555981,0.763439,0.091167
12,NATIVE,2024,PORTFOLIO,MIXED_50_50,54,55296,81230.226976,25934.226976,125934.226976,0.259342,...,0.102689,8,4.0,14,4,4,0.213292,0.570410,0.777943,0.092716
13,NATIVE,2024,R0_CONTROL,R0_COMPARATOR,54,55296,73811.789290,18515.789290,118515.789290,0.185158,...,0.108645,10,6.8,33,33,33,0.187388,0.584795,0.815713,0.095711
14,NATIVE,2024,R3_CONTROL,R3_STANDALONE,54,55296,108366.476664,53070.476664,153070.476664,0.530705,...,0.096271,8,4.7,22,1,1,0.319762,0.686073,0.871480,0.148185
15,NATIVE,2025,C1E3_SECONDARY,C1E3_STANDALONE,56,57344,49289.140194,-8054.859806,91945.140194,-0.080549,...,0.148013,17,8.0,27,27,27,0.268720,0.625001,0.866510,0.119129
16,NATIVE,2025,PORTFOLIO,FRACTIONAL_50_50,56,57344,40832.615121,-16511.384879,83488.615121,-0.165114,...,0.176896,9,7.0,56,56,56,0.136848,0.528751,0.752505,0.074936
17,NATIVE,2025,PORTFOLIO,MIXED_50_50,56,57344,44896.521740,-12447.478260,87552.521740,-0.124475,...,0.138001,11,9.2,45,45,45,0.196674,0.540733,0.787414,0.087531
18,NATIVE,2025,R0_CONTROL,R0_COMPARATOR,56,57344,38311.047101,-19032.952899,80967.047101,-0.190330,...,0.205206,14,11.2,54,54,54,0.288330,0.734212,0.945453,0.144465
19,NATIVE,2025,R3_CONTROL,R3_STANDALONE,56,57344,35298.003335,-22045.996665,77954.003335,-0.220460,...,0.277110,14,10.0,56,56,56,0.316609,0.779075,0.967586,0.163626
20,NATIVE,2026,C1E3_SECONDARY,C1E3_STANDALONE,61,62464,73054.078029,10590.078029,110590.078029,0.105901,...,0.144321,7,7.0,31,0,0,0.192998,0.565122,0.790505,0.087783
21,NATIVE,2026,PORTFOLIO,FRACTIONAL_50_50,61,62464,73332.429843,10868.429843,110868.429843,0.108684,...,0.121984,7,6.7,31,0,0,0.204134,0.516695,0.747957,0.083456
22,NATIVE,2026,PORTFOLIO,MIXED_50_50,61,62464,73812.526535,11348.526535,111348.526535,0.113485,...,0.125953,8,6.8,31,0,0,0.191015,0.514133,0.756249,0.080622
23,NATIVE,2026,R0_CONTROL,R0_COMPARATOR,61,62464,111527.742167,49063.742167,149063.742167,0.490637,...,0.089778,11,8.3,24,0,0,0.189731,0.572651,0.835199,0.098149
24,NATIVE,2026,R3_CONTROL,R3_STANDALONE,61,62464,80205.968811,17741.968811,117741.968811,0.177420,...,0.140585,14,11.6,32,0,0,0.234385,0.682782,0.940928,0.121644
25,NATIVE,PRE_2025,C1E3_SECONDARY,C1E3_STANDALONE,151,154624,200852.300875,46228.300875,146228.300875,0.462283,...,0.208201,11,6.0,62,31,31,0.189142,0.475594,0.625629,0.069914
26,NATIVE,PRE_2025,PORTFOLIO,FRACTIONAL_50_50,151,154624,200036.905730,45412.905730,145412.905730,0.454129,...,0.212721,8,6.0,54,4,4,0.152318,0.415555,0.572551,0.052568
27,NATIVE,PRE_2025,PORTFOLIO,MIXED_50_50,151,154624,207290.797417,52666.797417,152666.797417,0.526668,...,0.231725,9,7.0,54,4,4,0.146988,0.440394,0.601105,0.058036
28,NATIVE,PRE_2025,R0_CONTROL,R0_COMPARATOR,151,154624,140894.061009,-13729.938991,86270.061009,-0.137299,...,0.419608,18,14.0,151,151,151,0.098169,0.393561,0.583649,0.048365
29,NATIVE,PRE_2025,R3_CONTROL,R3_STANDALONE,151,154624,209295.399779,54671.399779,154671.399779,0.546714,...,0.352882,19,18.0,76,1,1,0.291160,0.621215,0.777060,0.130057
30,NATIVE,EXTENSION_2025_2026,C1E3_SECONDARY,C1E3_STANDALONE,117,119808,122343.218222,2535.218222,102535.218222,0.025352,...,0.276239,17,7.0,88,88,88,0.115244,0.399896,0.593918,0.050635
31,NATIVE,EXTENSION_2025_2026,PORTFOLIO,FRACTIONAL_50_50,117,119808,114165.044964,-5642.955036,94357.044964,-0.056430,...,0.277570,9,7.0,117,117,117,0.131123,0.342163,0.532055,0.044020
32,NATIVE,EXTENSION_2025_2026,PORTFOLIO,MIXED_50_50,117,119808,118709.048275,-1098.951725,98901.048275,-0.010990,...,0.244601,11,7.8,106,106,106,0.118772,0.348484,0.554145,0.043691
33,NATIVE,EXTENSION_2025_2026,R0_CONTROL,R0_COMPARATOR,117,119808,149838.789268,30030.789268,130030.789268,0.300308,...,0.264165,14,10.3,88,0,0,0.141220,0.451803,0.667504,0.063819
34,NATIVE,EXTENSION_2025_2026,R3_CONTROL,R3_STANDALONE,117,119808,115503.972146,-4304.027854,95695.972146,-0.043040,...,0.344080,14,11.9,117,117,117,0.162757,0.508414,0.746172,0.073937
35,NATIVE,ALL,C1E3_SECONDARY,C1E3_STANDALONE,268,274432,323195.519098,48763.519098,148763.519098,0.487635,...,0.217745,17,7.0,148,148,148,0.117544,0.313715,0.448778,0.034257
36,NATIVE,ALL,PORTFOLIO,FRACTIONAL_50_50,268,274432,314201.950694,39769.950694,139769.950694,0.397700,...,0.212721,9,7.0,121,121,121,0.096973,0.280631,0.398975,0.027119
37,NATIVE,ALL,PORTFOLIO,MIXED_50_50,268,274432,325999.845692,51567.845692,151567.845692,0.515678,...,0.231725,11,7.6,121,121,121,0.093464,0.297601,0.416714,0.029258
38,NATIVE,ALL,R0_CONTROL,R0_COMPARATOR,268,274432,290732.850277,16300.850277,116300.850277,0.163009,...,0.419608,18,11.6,242,0,0,0.072782,0.271166,0.425130,0.028310
39,NATIVE,ALL,R3_CONTROL,R3_STANDALONE,268,274432,324799.371925,50367.371925,150367.371925,0.503674,...,0.352882,19,14.9,118,118,118,0.187619,0.430023,0.581101,0.063354

In [4]:
pd.read_csv(OUT/'matched_contrasts.csv')

,scope,subject_schedule,reference_schedule,contrast,issues,subject_pnl_cny,reference_pnl_cny,matched_lift_cny,matched_ex_largest_lift_cny,largest_abs_paired_delta_cny,moving_block_p05_lift_cny
0,PRE_2025,MIXED_50_50,R3_STANDALONE,vs_R3,151,52666.797417,54671.399779,-2004.602362,28464.588693,30469.191055,-581.646123
1,PRE_2025,MIXED_50_50,C1E3_STANDALONE,vs_C1E3,151,52666.797417,46228.300875,6438.496541,-24030.694514,30469.191055,-440.122088
2,PRE_2025,MIXED_50_50,R0_COMPARATOR,vs_R0,151,52666.797417,-13729.938991,66396.736408,35927.545352,30469.191055,-82.082163
3,EXTENSION_2025_2026,MIXED_50_50,R3_STANDALONE,vs_R3,117,-1098.951725,-4304.027854,3205.076129,-5624.923975,8830.000104,-209.166976
4,EXTENSION_2025_2026,MIXED_50_50,C1E3_STANDALONE,vs_C1E3,117,-1098.951725,2535.218222,-3634.169947,-9222.011424,5587.841477,-207.489878
5,EXTENSION_2025_2026,MIXED_50_50,R0_COMPARATOR,vs_R0,117,-1098.951725,30030.789268,-31129.740993,-9969.504276,21160.236717,-756.661589
6,ALL,MIXED_50_50,R3_STANDALONE,vs_R3,268,51567.845692,50367.371925,1200.473767,31669.664822,30469.191055,-328.674679
7,ALL,MIXED_50_50,C1E3_STANDALONE,vs_C1E3,268,51567.845692,48763.519098,2804.326594,-27664.864461,30469.191055,-273.761774
8,ALL,MIXED_50_50,R0_COMPARATOR,vs_R0,268,51567.845692,16300.850277,35266.995415,4797.804359,30469.191055,-246.728909

In [5]:
pd.read_csv(OUT/'correlations.csv')

,scope,issues,pearson_issue_pnl,spearman_issue_pnl,downside_issues,pearson_downside_pnl,simultaneous_profit_rate,simultaneous_loss_rate,underwater_state_overlap_rate,top5_payout_issue_overlap,top10_payout_issue_overlap
0,ALL,268,0.075956,0.366233,241,-0.04319,0.100746,0.690299,0.932836,0.2,0.2

In [6]:
pd.read_csv(OUT/'integer_fractional_reconciliation.csv')

,scope,issues,integer_stake_cny,fractional_stake_cny,integer_pnl_cny,fractional_pnl_cny,integer_roi,fractional_roi,integer_r3_pnl_cny,fractional_r3_pnl_cny,integer_c1e3_pnl_cny,fractional_c1e3_pnl_cny,integer_unit_effect_pnl_cny
0,PRE_2025,151,154624,154624,52666.797417,45412.905730,0.340612,0.293699,27335.699889,27335.699889,25331.097527,18077.205840,7253.891687
1,EXTENSION_2025_2026,117,119808,119808,-1098.951725,-5642.955036,-0.009173,-0.047100,-2152.013927,-2152.013927,1053.062202,-3490.941109,4544.003311
2,ALL,268,274432,274432,51567.845692,39769.950694,0.187908,0.144917,25183.685963,25183.685963,26384.159729,14586.264731,11797.894998

In [7]:
pd.read_csv(OUT/'decision_gates.csv')

                                        gate  passed
0                           R3_2025_positive   False
1                         C1E3_2025_positive   False
2                           R3_2026_positive    True
3                         C1E3_2026_positive    True
4                      R3_extension_positive   False
5                    C1E3_extension_positive    True
6                            R3_all_positive    True
7                          C1E3_all_positive    True
8           R3_extension_ex_largest_positive   False
9         C1E3_extension_ex_largest_positive   False
10                  mixed_extension_positive   False
11                        mixed_all_positive    True
12       mixed_extension_ex_largest_positive   False
13             mixed_all_ex_largest_positive    True
14         mixed_maxdd_below_each_standalone   False
15             r3_c1e3_correlation_below_one    True
16         diversification_not_mere_dilution   False
17         no_annual_extension_year_reversal   False
18    moving_block_p05_vs_r3_ext_nonnegative   False
19  moving_block_p05_vs_c1e3_ext_nonnegative   False
20    moving_block_p05_vs_r3_all_nonnegative   False
21  moving_block_p05_vs_c1e3_all_nonnegative   False
22             extension_confirms_pre2025_r3   False
23              extension_weakens_pre2025_r3    True
24             extension_reverses_pre2025_r3    True
25           extension_confirms_pre2025_c1e3    True
26           extension_reverses_pre2025_c1e3   False
27                   no_promotion_authorized    True

In [8]:
pd.read_csv(OUT/'issue_ledger.csv').assign(issue=lambda d: d['issue'].astype(str)).query("issue >= '25011' & issue <= '25125'").sort_values('issue')

,issue,issue_year,inclusion_status,reason,panel_fixtures,supported_fixtures,selected_match_ids,excluded_selected_fixture,exclusion_reason,exclusion_source_payload_sha256,exclusion_source_row_evidence,downstream_eligible_396
172,25011,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,176,176,53|60|86|114|126|161|176,NaN,NaN,NaN,NaN,True
173,25012,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,206,206,11|50|114|115|125|157|194,NaN,NaN,NaN,NaN,True
174,25013,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,279,279,51|61|88|116|247|253|275,NaN,NaN,NaN,NaN,True
175,25014,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,350,350,20|33|58|135|289|336|346,NaN,NaN,NaN,NaN,True
176,25021,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,270,270,36|121|140|163|210|217|224,NaN,NaN,NaN,NaN,True
177,25022,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,398,398,17|200|314|341|352|373|391,NaN,NaN,NaN,NaN,True
178,25023,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,412,412,25|28|75|100|151|237|241,NaN,NaN,NaN,NaN,True
179,25024,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,80,80,3|23|24|43|50|68|80,NaN,NaN,NaN,NaN,True
180,25031,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,354,354,102|170|192|227|279|323|350,NaN,NaN,NaN,NaN,True
181,25032,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,413,413,15|65|170|237|327|388|396,NaN,NaN,NaN,NaN,True
182,25033,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,407,407,60|75|211|256|366|379|398,NaN,NaN,NaN,NaN,True
183,25034,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,116,116,3|21|22|45|66|69|116,NaN,NaN,NaN,NaN,True
184,25035,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,369,369,6|61|92|139|226|350|360,NaN,NaN,NaN,NaN,True
185,25041,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,548,548,75|184|198|434|458|512|537,NaN,NaN,NaN,NaN,True
186,25042,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,476,476,60|81|84|122|276|303|423,NaN,NaN,NaN,NaN,True
187,25043,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,475,475,158|234|263|275|376|421|471,NaN,NaN,NaN,NaN,True
188,25044,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,473,473,30|68|146|161|274|337|442,NaN,NaN,NaN,NaN,True
189,25051,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,460,460,37|88|130|262|304|305|371,NaN,NaN,NaN,NaN,True
190,25052,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,417,417,69|79|116|125|222|276|367,NaN,NaN,NaN,NaN,True
191,25053,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,451,451,22|40|53|55|237|305|448,NaN,NaN,NaN,NaN,True
192,25054,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,324,324,50|80|102|177|181|269|284,NaN,NaN,NaN,NaN,True
193,25055,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,76,76,6|8|38|44|56|59|67,NaN,NaN,NaN,NaN,True
194,25061,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,158,158,43|44|46|97|112|119|124,NaN,NaN,NaN,NaN,True
195,25062,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,65,65,12|21|27|54|59|60|62,NaN,NaN,NaN,NaN,True
196,25063,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,161,161,11|43|77|79|152|153|155,NaN,NaN,NaN,NaN,True
197,25064,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,175,175,35|48|107|150|152|166|170,NaN,NaN,NaN,NaN,True
198,25065,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,37,37,2|14|17|18|20|27|38,NaN,NaN,NaN,NaN,True
199,25071,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,122,122,5|46|53|63|81|97|102,NaN,NaN,NaN,NaN,True
200,25072,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,116,116,18|23|64|68|101|106|112,NaN,NaN,NaN,NaN,True
201,25073,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,146,146,1|57|60|110|115|121|123,NaN,NaN,NaN,NaN,True
202,25074,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,215,215,58|63|71|72|89|116|211,NaN,NaN,NaN,NaN,True
203,25075,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,239,239,24|53|56|130|134|200|206,NaN,NaN,NaN,NaN,True
204,25081,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,252,252,3|17|38|42|180|221|249,NaN,NaN,NaN,NaN,True
205,25082,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,348,348,27|39|57|202|204|219|298,NaN,NaN,NaN,NaN,True
206,25083,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,419,419,13|43|126|128|151|354|363,NaN,NaN,NaN,NaN,True
207,25084,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,438,438,56|238|262|274|373|378|401,NaN,NaN,NaN,NaN,True
208,25085,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,70,70,7|12|35|38|57|63|68,NaN,NaN,NaN,NaN,True
209,25091,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,387,387,24|25|94|181|202|342|374,NaN,NaN,NaN,NaN,True
210,25092,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,119,119,22|26|28|31|103|107|111,NaN,NaN,NaN,NaN,True
211,25093,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,401,401,30|69|118|202|230|338|391,NaN,NaN,NaN,NaN,True
212,25094,2025,EXCLUDED,2025_EXCLUDED_SELECTED_FIXTURE_EXCLUDED:440:UN...,437,437,14|28|84|100|179|300|440,440.0,UNRESOLVED_NATIVE_SETTLEMENT_ABSENT_ON_500_PAGE,9f9fa56cbfc0cec05e5961771fd2269cd8cb1b38f24bac...,440 阿职联 09-23 08:00 贝尔格拉诺 0 纽维尔老男孩 - 1.80 3.25...,True
213,25095,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,530,530,75|84|141|169|172|348|361,NaN,NaN,NaN,NaN,True
214,25101,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,148,148,16|73|75|77|89|104|121,NaN,NaN,NaN,NaN,True
215,25102,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,160,160,2|31|47|51|62|142|149,NaN,NaN,NaN,NaN,True
216,25103,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,412,412,83|207|212|326|331|388|389,NaN,NaN,NaN,NaN,True
217,25104,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,457,457,39|147|215|307|394|435|452,NaN,NaN,NaN,NaN,True
218,25105,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,132,132,1|35|47|49|80|83|131,NaN,NaN,NaN,NaN,True
219,25111,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,344,344,33|46|90|114|146|151|288,NaN,NaN,NaN,NaN,True
220,25112,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,429,429,22|34|44|50|251|270|345,NaN,NaN,NaN,NaN,True
221,25113,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,102,102,20|65|66|67|69|94|97,NaN,NaN,NaN,NaN,True
222,25114,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,304,304,12|43|46|132|143|147|248,NaN,NaN,NaN,NaN,True
223,25115,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,81,81,14|21|36|39|47|66|81,NaN,NaN,NaN,NaN,True
224,25121,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,260,260,60|70|129|169|196|217|257,NaN,NaN,NaN,NaN,True
225,25122,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,335,335,10|66|85|128|300|302|336,NaN,NaN,NaN,NaN,True
226,25123,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,299,299,30|48|78|108|214|226|273,NaN,NaN,NaN,NaN,True
227,25124,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,214,214,27|29|60|61|172|177|203,NaN,NaN,NaN,NaN,True
228,25125,2025,INCLUDED,2025_INCLUDED_396_CANONICAL_SETTLEMENT_COMPLETE,131,131,16|51|87|96|120|122|127,NaN,NaN,NaN,NaN,True

In [9]:
pd.read_csv(OUT/'selected_fixture_receipt.csv').head(40)

,issue,issue_year,disposition,all_selected_settled,selected_match_ids,match_idx,settlement_available,fixture_excluded,exclusion_reason,exclusion_source_url,exclusion_source_payload_sha256,exclusion_source_row_evidence
0,22011,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,20|24|29|38|39|50|59,20,True,False,NaN,NaN,NaN,NaN
1,22011,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,20|24|29|38|39|50|59,24,True,False,NaN,NaN,NaN,NaN
2,22011,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,20|24|29|38|39|50|59,29,True,False,NaN,NaN,NaN,NaN
3,22011,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,20|24|29|38|39|50|59,38,True,False,NaN,NaN,NaN,NaN
4,22011,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,20|24|29|38|39|50|59,39,True,False,NaN,NaN,NaN,NaN
5,22011,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,20|24|29|38|39|50|59,50,True,False,NaN,NaN,NaN,NaN
6,22011,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,20|24|29|38|39|50|59,59,False,False,NaN,NaN,NaN,NaN
7,22012,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,19|30|35|73|89|156|176,19,True,False,NaN,NaN,NaN,NaN
8,22012,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,19|30|35|73|89|156|176,30,True,False,NaN,NaN,NaN,NaN
9,22012,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,19|30|35|73|89|156|176,35,True,False,NaN,NaN,NaN,NaN
10,22012,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,19|30|35|73|89|156|176,73,True,False,NaN,NaN,NaN,NaN
11,22012,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,19|30|35|73|89|156|176,89,True,False,NaN,NaN,NaN,NaN
12,22012,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,19|30|35|73|89|156|176,156,False,False,NaN,NaN,NaN,NaN
13,22012,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,19|30|35|73|89|156|176,176,True,False,NaN,NaN,NaN,NaN
14,22013,2022,INCLUDED,True,41|47|79|139|151|180|188,41,True,False,NaN,NaN,NaN,NaN
15,22013,2022,INCLUDED,True,41|47|79|139|151|180|188,47,True,False,NaN,NaN,NaN,NaN
16,22013,2022,INCLUDED,True,41|47|79|139|151|180|188,79,True,False,NaN,NaN,NaN,NaN
17,22013,2022,INCLUDED,True,41|47|79|139|151|180|188,139,True,False,NaN,NaN,NaN,NaN
18,22013,2022,INCLUDED,True,41|47|79|139|151|180|188,151,True,False,NaN,NaN,NaN,NaN
19,22013,2022,INCLUDED,True,41|47|79|139|151|180|188,180,True,False,NaN,NaN,NaN,NaN
20,22013,2022,INCLUDED,True,41|47|79|139|151|180|188,188,True,False,NaN,NaN,NaN,NaN
21,22014,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,1|68|77|89|171|228|246,1,False,False,NaN,NaN,NaN,NaN
22,22014,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,1|68|77|89|171|228|246,68,True,False,NaN,NaN,NaN,NaN
23,22014,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,1|68|77|89|171|228|246,77,True,False,NaN,NaN,NaN,NaN
24,22014,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,1|68|77|89|171|228|246,89,True,False,NaN,NaN,NaN,NaN
25,22014,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,1|68|77|89|171|228|246,171,True,False,NaN,NaN,NaN,NaN
26,22014,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,1|68|77|89|171|228|246,228,True,False,NaN,NaN,NaN,NaN
27,22014,2022,EXCLUDED_SELECTED_FIXTURE_UNSETTLED,False,1|68|77|89|171|228|246,246,True,False,NaN,NaN,NaN,NaN
28,22015,2022,INCLUDED,True,76|85|87|105|120|130|144,76,True,False,NaN,NaN,NaN,NaN
29,22015,2022,INCLUDED,True,76|85|87|105|120|130|144,85,True,False,NaN,NaN,NaN,NaN
30,22015,2022,INCLUDED,True,76|85|87|105|120|130|144,87,True,False,NaN,NaN,NaN,NaN
31,22015,2022,INCLUDED,True,76|85|87|105|120|130|144,105,True,False,NaN,NaN,NaN,NaN
32,22015,2022,INCLUDED,True,76|85|87|105|120|130|144,120,True,False,NaN,NaN,NaN,NaN
33,22015,2022,INCLUDED,True,76|85|87|105|120|130|144,130,True,False,NaN,NaN,NaN,NaN
34,22015,2022,INCLUDED,True,76|85|87|105|120|130|144,144,True,False,NaN,NaN,NaN,NaN
35,22021,2022,INCLUDED,True,10|46|71|102|170|328|337,10,True,False,NaN,NaN,NaN,NaN
36,22021,2022,INCLUDED,True,10|46|71|102|170|328|337,46,True,False,NaN,NaN,NaN,NaN
37,22021,2022,INCLUDED,True,10|46|71|102|170|328|337,71,True,False,NaN,NaN,NaN,NaN
38,22021,2022,INCLUDED,True,10|46|71|102|170|328|337,102,True,False,NaN,NaN,NaN,NaN
39,22021,2022,INCLUDED,True,10|46|71|102|170|328|337,170,True,False,NaN,NaN,NaN,NaN

All outcomes are exposed historical evidence: 2022-2024 parity and 2025-2026 retrospective extension. The notebook does not authorize promotion.